apiVersion: v1
kind: Service

metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/version: 1.8.2

spec:
  selector:
    app.kubernetes.io/name: cert-manager-webhook
    app.kubernetes.io/part-of: cert-manager

  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
