apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: restic
  namespace: velero
  labels:
    app.kubernetes.io/name: restic
    app.kubernetes.io/part-of: velero
    app.kubernetes.io/version: 1.9.2

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: restic
      app.kubernetes.io/part-of: velero

  template:
    metadata:
      labels:
        app.kubernetes.io/name: restic
        app.kubernetes.io/part-of: velero
        app.kubernetes.io/version: 1.9.2

    spec:
      serviceAccountName: velero

      securityContext:
        runAsUser: 0

      volumes:
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: wasabi-credentials
          secret:
            secretName: wasabi-credentials
        - name: scratch
          emptyDir: {}

      volumeMounts:
        - name: host-pods
          mountPath: /host_pods
          mountPropagation: HostToContainer
        - name: wasabi-credentials
          mountPath: /credentials
        - name: scratch
          mountPath: /scratch

      containers:
        - name: restic
          image: velero/velero:v1.9.2

          command:
            - /velero
          args:
            - restic
            - server

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: VELERO_SCRATCH_DIR
              value: /scratch

          volumeMounts:
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: wasabi-credentials
              mountPath: /credentials
            - name: scratch
              mountPath: /scratch
