apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: restic
  namespace: velero

spec:
  selector:
    matchLabels:
      name: restic

  template:
    metadata:
      labels:
        component: velero
        name: restic

    spec:
      serviceAccountName: velero

      securityContext:
        runAsUser: 0

      volumes:
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - name: scratch
          emptyDir: {}

      volumeMounts:
        - name: host-pods
          mountPath: /host_pods
          mountPropagation: HostToContainer
        - name: cloud-credentials
          mountPath: /credentials
        - name: scratch
          mountPath: /scratch

      containers:
        - name: restic
          image: velero/velero:v1.9.0

          command:
            - /velero
          args:
            - restic
            - server

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud-credentials
            - name: VELERO_SCRATCH_DIR
              value: /scratch

          volumeMounts:
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: cloud-credentials
              mountPath: /credentials
            - name: scratch
              mountPath: /scratch
