apiVersion: apps/v1
kind: Deployment

metadata:
  name: velero
  namespace: velero

spec:
  selector:
    matchLabels:
      deploy: velero

  template:
    metadata:
      labels:
        component: velero
        deploy: velero

    spec:
      serviceAccountName: velero

      volumes:
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
        - emptyDir: {}
          name: scratch
        - emptyDir: {}
          name: plugins

      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.5.0

          volumeMounts:
            - mountPath: /target
              name: plugins

      containers:
        - name: velero
          image: velero/velero:v1.9.0

          command:
            - /velero
          args:
            - server

          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: LD_LIBRARY_PATH
              value: /plugins

          volumeMounts:
            - mountPath: /credentials
              name: cloud-credentials
            - mountPath: /scratch
              name: scratch
            - mountPath: /plugins
              name: plugins
