apiVersion: apps/v1
kind: Deployment

metadata:
  name: velero
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: velero
    app.kubernetes.io/version: 1.9.2

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
      app.kubernetes.io/part-of: velero

  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
        app.kubernetes.io/part-of: velero
        app.kubernetes.io/version: 1.9.2

    spec:
      serviceAccountName: velero

      volumes:
        - name: wasabi-credentials
          secret:
            secretName: wasabi-credentials
        - emptyDir: {}
          name: scratch
        - emptyDir: {}
          name: plugins

      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.5.1

          volumeMounts:
            - mountPath: /target
              name: plugins

      containers:
        - name: velero
          image: velero/velero:v1.9.2

          command:
            - /velero
          args:
            - server

          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: LD_LIBRARY_PATH
              value: /plugins

          volumeMounts:
            - mountPath: /credentials
              name: wasabi-credentials
            - mountPath: /scratch
              name: scratch
            - mountPath: /plugins
              name: plugins
