apiVersion: velero.io/v1
kind: Schedule

metadata:
  name: daily
  namespace: velero
  labels:
    app.kubernetes.io/part-of: velero

spec:
  schedule: "0 22 * * *"
  useOwnerReferencesInBackup: false

  template:
    includedNamespaces:
      - "*"
    ttl: 0s
