apiVersion: velero.io/v1
kind: Schedule

metadata:
  name: daily
  namespace: velero

spec:
  schedule: "0 22 * * *"
  useOwnerReferencesInBackup: false

  template:
    includedNamespaces:
      - "*"
    ttl: 0s
