apiVersion: v1
kind: Secret
metadata:
    name: searxng-redis-env
    namespace: medium-place
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:I9KD5eSu6RepkpkhKzsDPVH9JyBOx5OkFMhFIcNwUi5WjtOdhxn57Eh4G82x0RRQ4Zcux79V/irccNdyusTibw==,iv:yWUroOzgF7gtojp6RXX9KlGsu8XXpdR4ogmcSq3fy2I=,tag:Fbq+E2Ahf/KrdJaXlSO1+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERWllanA4bHlPNTRPeFpU
            aGNUV25ySEVxRTRycDFWbzE3VG5aRDZVV0gwCmJGSXdCN2FDcFNodExqOWpJWTFN
            MVlpMzNjd1ZrUElGQlpNZVZDeWNhKzAKLS0tIFo5V3dSajZYK2ZYUHg5V2Z3RFlp
            NzlRMVFjK0lyWHhWUDhtdmJzQUkzbDQKTzWM4hTwNwXNGxnET1FXZ9hW3LpqBzFB
            uns+3qON8BaJ0wrlRLyTSkXkdeWxCcEMzvS3OevwwJEh22EwtpgX0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-23T00:03:59Z"
    mac: ENC[AES256_GCM,data:YjUNBiPVI0IiKL+Nd8Z8VOTjOtXj1VKy6uOQDYkzhul8bXnXfeN38l5X24xUo1jrVdsunFYLpVk2UaTAH5pbQKDT7v3cU/DKUor+zk3vUvb7v8MFpUOKd8e4fpKGJrVFcY3HGkaI4Utaeq4AAFhvXSAVxBiZlMJtkLTXAUb0oa4=,iv:MCNZlEM4CpF38UoQtjQDOdpFtfe6TssZ2TI1IH+0Lzs=,tag:qqa8SGHuTtjzC5pxFSrs1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
