apiVersion: v1
kind: Service

metadata:
  name: searxng-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: searxng
    app.kubernetes.io/version: 6.2.7

spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: searxng

  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
