apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-public
  namespace: contour-public

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.1.6

  values:
    ingress:
      ingressClassName: public
    envoy:
      service:
        annotations:
          load-balancer.hetzner.cloud/name: contour-public
          load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
          load-balancer.hetzner.cloud/use-private-ip: "true"
          load-balancer.hetzner.cloud/disable-private-ingress: "true"
          load-balancer.hetzner.cloud/ipv6-disabled: "true"
          load-balancer.hetzner.cloud/location: fsn1
          load-balancer.hetzner.cloud/type: lb11
        clusterIP: 10.96.0.50

 
