apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-public
  namespace: contour-public

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.1.6

  values:
    ingress:
      ingressClassName: public
    envoy:
      service:
        clusterIP: 10.96.0.100

 
