apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
  labels:
    app.kubernetes.io/part-of: nginx-ingress-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-controller

subjects:
  - kind: ServiceAccount
    name: nginx-ingress-controller
    namespace: nginx-ingress-controller
