apiVersion: apps/v1
kind: Deployment

metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/version: 1.9.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: cert-manager

  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/version: 1.9.1

    spec:
      serviceAccountName: cert-manager

      terminationGracePeriodSeconds: 60

      containers:
        - name: cert-manager

          imagePullPolicy: Always
          image: bitnami/cert-manager:1.9.1
          args:
            - --v=2
            - --leader-elect=false
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --acme-http01-solver-image=bitnami/acmesolver:1.9.1

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          ports:
            - name: http
              protocol: TCP
              containerPort: 9402
