apiVersion: apps/v1
kind: Deployment

metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/version: 1.8.2

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: cert-manager

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+-debian-\\d+-r\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/version: 1.8.2

    spec:
      serviceAccountName: cert-manager

      terminationGracePeriodSeconds: 60

      containers:
        - name: cert-manager
          image: bitnami/cert-manager:1.8.2-debian-11-r8

          args:
            - --v=2
            - --leader-elect=false
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --acme-http01-solver-image=bitnami/acmesolver:1.8.2-debian-11-r9

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          ports:
            - name: http
              protocol: TCP
              containerPort: 9402
