apiVersion: v1
kind: Service

metadata:
  name: cert-manager-metrics
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/version: 1.9.1

spec:
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager

  ports:
    - name: http
      protocol: TCP
      port: 9402
      targetPort: http
