apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/part-of: nginx-ingress-controller

configMapGenerator:
  - name: nginx-private-config
    namespace: nginx-ingress-controller
    files:
      - configuration/nginx.conf
