apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: caddy
  namespace: medium-place
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: 100
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/part-of: caddy

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - medium.place
        - ingress.nutria.cloud
      secretName: medium.place-tls

  rules:
    - host: medium.place
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: caddy
                port:
                  name: http
    - host: ingress.nutria.cloud
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: caddy
                port:
                  name: http
