apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generatorOptions:
  labels:
    app.kubernetes.io/part-of: caddy

configMapGenerator:
  - name: caddy-config
    namespace: medium-place
    files:
      - configuration/Caddyfile
