kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: caddy-ingress-controller

roleRef:
  kind: ClusterRole
  name: caddy-ingress-controller
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: ServiceAccount
  name: caddy-ingress-controller
  namespace: caddy-ingress-controller
