apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: caddy-ingress-controller

rules:
  - apiGroups:
      - ""
      - "networking.k8s.io"
      - "coordination.k8s.io"
    resources:
      - ingresses
      - ingresses/status
      - secrets
      - leases
    verbs: ["*"]

  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - nodes
      - routes
      - extensions
      - configmaps
    verbs:
      - list
      - get
      - watch
