apiVersion: v1
kind: Service

metadata:
  name: caddy-ingress-controller
  namespace: caddy-ingress-controller
  labels:
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/part-of: caddy-ingress-controller
    app.kubernetes.io/version: 0.1.3

spec:
  selector:
    app.kubernetes.io/name: caddy-ingress-controller
    app.kubernetes.io/part-of: caddy-ingress-controller

  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https

