apiVersion: v1
kind: Service

metadata:
  name: synapse-whatsapp-bridge
  namespace: medium-place
  labels:
    app.kubernetes.io/name: whatsapp-bridge
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/version: 0.6.1

spec:
  selector:
    app.kubernetes.io/name: whatsapp-bridge
    app.kubernetes.io/part-of: synapse

  ports:
    - name: http
      protocol: TCP
      port: 29318
      targetPort: http
