apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: hcloud-csi
  labels:
    app.kubernetes.io/part-of: hcloud-csi

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hcloud-csi

subjects:
  - kind: ServiceAccount
    name: hcloud-csi
    namespace: kube-system
