apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: stolon-keeper
  namespace: stolon
  labels:
    app.kubernetes.io/part-of: stolon

rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
