apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: stolon-keeper
  namespace: stolon
  labels:
    app.kubernetes.io/name: stolon-keeper
    app.kubernetes.io/part-of: stolon
    app.kubernetes.io/version: 0.17.0

spec:
  replicas: 3

  serviceName: stolon-keeper

  selector:
    matchLabels:
      app.kubernetes.io/name: stolon-keeper
      app.kubernetes.io/part-of: stolon

  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
      labels:
        app.kubernetes.io/name: stolon-keeper
        app.kubernetes.io/part-of: stolon
        app.kubernetes.io/version: 0.17.0
        stolon-cluster: nutria
        component: stolon-keeper

    spec:
      serviceAccountName: stolon-keeper

      terminationGracePeriodSeconds: 60

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - stolon-keeper

      containers:
        - name: stolon-keeper

          image: cschmatzler/stolon:0.17.0-pg14-r2
          command:
            - "/bin/bash"
            - "-ec"
            - |
              IFS='-' read -ra ADDR <<< "$(hostname)"
              export STKEEPER_UID="keeper${ADDR[-1]}"
              export POD_IP=$(hostname -i)
              export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
              chown stolon:stolon $STOLON_DATA
              exec gosu stolon stolon-keeper --data-dir $STOLON_DATA

          volumeMounts:
            - mountPath: /stolon-data
              name: data

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STOLON_DATA
              value: /stolon-data
            - name: STKEEPER_CLUSTER_NAME
              value: nutria
            - name: STKEEPER_STORE_BACKEND
              value: kubernetes
            - name: STKEEPER_KUBE_NAMESPACE
              value: stolon
            - name: STKEEPER_KUBE_RESOURCE_KIND
              value: configmap
            - name: STKEEPER_PG_SU_USERNAME
              value: postgres
            - name: STKEEPER_PG_REPL_USERNAME
              value: replication
          envFrom:
            - secretRef:
                name: stolon-keeper-env

          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432

  volumeClaimTemplates:
    - metadata:
        name: data

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 3Gi
