apiVersion: v1
kind: Secret
metadata:
    name: stolon-keeper-env
    namespace: stolon
data:
    STKEEPER_PG_SU_PASSWORD: ENC[AES256_GCM,data:snNvvyB/n9Q5jTD8G5z3hSY1qhLmTLTdNUhQLERLd8vfh4XmKGP1jcVmPbo1wB4vczBDwZMUUYdTU5+NI7YQcg==,iv:b3WvHfmei075NsKhg4s311beRS3GKqyCd7ZOrlspHV4=,tag:SQhZm51ne6mOJoiD3GeScA==,type:str]
    STKEEPER_PG_REPL_PASSWORD: ENC[AES256_GCM,data:dlUQrQKkYvcD5y+fiEHjhF8bkF0HOlJMEavB6DPTXMFuNrqHL66jz55qbR0lqIX9hoLTbBH39WRqSenBhwUS8A==,iv:ZDRHmpEo7xnKGme/BbMwNePGz/yo+w4YNaSnbti5KOU=,tag:IqtEOfBeuig6zbMdmhOjwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZm5yQzJjZGZob2VKMGJM
            SlNZbmk0NW1OTDNOUXBJbENRWjBoeFdZZ3dBCmhiWXlTVldXSEVVQ053YzdacmJw
            UmgvYzAyQkNNZHhRYnJDeGFWZ1o5Vk0KLS0tIGJ0QWowblNlVXdRVTkray8yR3ll
            RjBkdk0wQm9oWTB6QzV0UEw3T2FMWDgKeJY2sxnHMAK0Z7OstTAIU5E/dnvKWGWg
            3xhbkIJh2piezvKdQPjWA5Nq96Jfzh0m/5Ci3WdwbStwmaj8V4e4EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T18:55:41Z"
    mac: ENC[AES256_GCM,data:qC80gACJCakwFCsZdjrDX7JfUf556zF5ln7LgQye6WvWoBRI60zNNTk9u1sOraUl3eAzM9qOD4gEs6kCP6yvuxQ3Unk9l4ayacuCm79nvQPQn0bHvEFp7sRmB+NEhEEIdE7jHtJbw8MQf8QCbMoQcIy2e8gvZKD4uI4sHhKhIbA=,iv:5riA6J1eW2o+SO5VfR0NwLjNeG7HJmUwgV5zJW6Bolo=,tag:pXgr6orZn1tJ+STsqyjv9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
