apiVersion: v1
kind: Secret
metadata:
    name: stolon-keeper-env
    namespace: stolon
data:
    STKEEPER_PG_SU_PASSWORD: ENC[AES256_GCM,data:1RlxJoIr1ew81JFYxNt/A/j9QEBvEGX235tZ2OhnXCMXTDAqSo8D6sjv/wH465HdFes7Z67BoDsswrNc6hl47Q==,iv:QBcffLb+GAzo3LcVZeBe1TDqU/k+nA97SOrAs9eja5Y=,tag:NEiuc6+StBli/lyAx4muog==,type:str]
    STKEEPER_PG_REPL_PASSWORD: ENC[AES256_GCM,data:RHehlUik5GIWapCktyLBMtbWwdUkeoxiyBtCcIKeijj6xpZc52oj8nVmDZWJXG81598bndkg24LK1/GkTd/OtA==,iv:MezKM94/jqT5VDMQDFfnDoADApsqKuSGZjnle+c6opo=,tag:mrC35TlnZ/DM3qhCcB75Gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbVpwdE15bEpQY0QySzhi
            UTNSS1lnN2RwazhjVERjVWRJWmh5UXR0bm00CmpLYndWM1BOZ3JQSUFvdlNValo4
            aE1HRGdRVjl6Y2RBQ1JINWhKV3pIRUEKLS0tIE51WHIyUHRBWU9rRVY2VWNIZGM0
            anJ5T1d0WmpZSXZ2VEdIbHpibHRJaFkKBJWhggDsxmZ5sByZuUdgYwlgOQrsZHHn
            3XHF4zvqJ4ZtxwJ/+T2l2i3jemKY0HjoNDqpWq29ueJRrw/7ecPC8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T16:57:33Z"
    mac: ENC[AES256_GCM,data:2xhe6Fd9ta1+PwU+corN0sWUxVafAusxsJRo2+JV8PSoHMQ2fj/s2SaB5mOk7rP4lAEsgrnYfmfPJNINMmcngK6f+sSYtZdhCIMb56N+onnDiUnrweOb4lQEVpXJk6D74LPwTttJF2bXbg+4vxtDDmqFFvE/J2XeOZPtNX3nkkg=,iv:0ZYmP3v6H4CuFx5f9lvOsStxZkatvcW/T0atDHrnipE=,tag:HbE7kM8/jfBAAiPlNHx+Dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
