apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: cainjector-leader-election
  namespace: cert-manager
  labels:
    app.kubernetes.io/part-of: cert-manager

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cainjector-leader-election

subjects:
  - kind: ServiceAccount
    name: cainjector
    namespace: cert-manager
