apiVersion: apps/v1
kind: Deployment

metadata:
  name: paperless-ngx-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: 7.0.4

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: paperless-ngx

  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: paperless-ngx
        app.kubernetes.io/version: 7.0.4

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: redis

          imagePullPolicy: Always
          image: bitnami/redis:7.0.4

          envFrom:
            - secretRef:
                name: paperless-ngx-redis-env

          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
