apiVersion: v1
kind: Service

metadata:
  name: paperless-ngx-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: 7.0.4

spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: paperless-ngx

  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis
