apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: forge
    namespace: medium-place
data:
    .dockerconfigjson: ENC[AES256_GCM,data:TcYchymFJyzEzfB1oJ6ETf1tIYbNwv2GX2EloGnGjJeQUxT6sxWINIo4p7AQ1GSFvq76907i47mov1A+7mX16oDt1NRlGZW4Lqegb/mpLG7++ixYuNyPct5lPCW8MbWsPV9KB5O8fIut3OTSe5648vO1JGbA8mj1YHJ2Cs5/VS49riG9blHgAjAR2/4uGbRUkXGbpllCoIR4Ygxf6OJEPMTQyK5hsVyC45OH7/ZF0V5+kVIwqydFPfXvTWS5FN2SsG23i+RrUHry9TiKxfEop8zxFr3g3l/29QgzDs4btiGO6Tq3uaq4KhfqeTpoUvryZ+Wgfy/ycQxv9FghYLtvSLCaD9p5GeX5aLpyXl1/Y9CjYQcrSXrUAhjUQtOl2PQzOf/QAQ==,iv:1d8dx49htAbZcmO1X9hbxFSPi8k6BNJw1IGKEStd/eI=,tag:OW+nkbt47MwHqPGI1yPXSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkU3l5VS9KQTBoVGtKSUtr
            MFUrYWNFSmhhbkhpUjBWdFRXREZVRlNCZEJBCllQZUpYbWpmQTNvRjYvSEhrV09R
            MGhvbG1LenhJc0g0Z3VvM2dGQVVadVkKLS0tIEZ4SWRHRlRGaHl1TFAzeWJzZDgr
            TlFhTEFoekU1R2pzdzhXWFNrSVVLMDgK+n5cRFO5vTpvxblCsFJmcJq+5TarY3Ky
            s1ZsvGQ8eyPvHOWe+RMCq9vEnjRbs6qXhu5M6NISuWkih7UqKy+0+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-06T18:23:48Z"
    mac: ENC[AES256_GCM,data:HlRZgvDTtEhlIUXYt6roSEE060iIE33Fn5JrkwUMo0N9JdKZw0z8o5LxrjCP+96l0oPWu/5mJZmaVxhjaFgMtKac3lGD0A/40n0WoKylrBfGU5Syl6AfS1dmpNX6rx2NtBDrlmLWRy/Q7NybmknCLQWSjVUr77Lz82qqH5TW8MM=,iv:6nHBNRcbKrEKYO81B4KVQZt26HDTc7zTJ47xyuk5/Hk=,tag:xdar+UMdT3f/zNx0t65QXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
