apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forge
  namespace: nutria-cloud
spec:
  chart:
    spec:
      chart: gitea
      sourceRef:
        kind: HelmRepository
        name: gitea
      version: 6.0.3
  upgrade:
    remediation:
      retries: 5
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  valuesFrom:
    - kind: Secret
      name: forge-values
