{{- if and .Values.ingress.host .Values.ingress.paths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "base.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ ternary "public" "private" (default false .Values.ingress.public) }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.host }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- $fullName := include "base.fullname" . -}}
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
          {{- end }}
{{- end }}
