apiVersion: networking.k8s.io/v1
kind: IngressClass

metadata:
  name: nginx-private
  labels:
    app.kubernetes.io/part-of: nginx-ingress-controller

spec:
  controller: k8s.io/ingress-nginx-private
