apiVersion: v1
kind: Service

metadata:
  name: nginx-ingress-controller-private
  namespace: nginx-ingress-controller
  labels:
    app.kubernetes.io/name: nginx-ingress-controller-private
    app.kubernetes.io/part-of: nginx-ingress-controller
    app.kubernetes.io/version: 1.3.1

spec:
  clusterIP: 10.96.0.30

  selector:
    app.kubernetes.io/name: nginx-ingress-controller-private
    app.kubernetes.io/part-of: nginx-ingress-controller

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
