apiVersion: v1
kind: Service

metadata:
  name: vikunja-frontend
  namespace: medium-place
  labels:
    app.kubernetes.io/name: vikunja-frontend
    app.kubernetes.io/part-of: vikunja
    app.kubernetes.io/version: 0.19.0

spec:
  selector:
    app.kubernetes.io/name: vikunja-frontend
    app.kubernetes.io/part-of: vikunja

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
