kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: authentik-redis-env
  namespace: medium-place
  creationTimestamp: null
spec:
  template:
    metadata:
      name: authentik-redis-env
      namespace: medium-place
      creationTimestamp: null
    data: null
  encryptedData:
    REDIS_PASSWORD: AgBDypzYI4NA+pJDeSp4MwkEAEUESTCoCBtG39Lu+XgAY+ZHrDIp5dsZ84ELgBErUhEcu1bGgm0Uiut5owTbXbNeLHWjK6JSPD8NHzNk5IAteKUxgc9ldBDqibYIfib42R1RvY4EZu7F6aGREPhXjXpFPDZn0Mnp9wDMnWX7KLBMvwdiTeOZbX86MlSR0E71P+FE2l7H2rZLSvVFlEKTJGXiTISdivwbdV74zDC+uqVwGOGJJBvE3oZYtTikxA6vAinirho5+XnROptj8galYYVCOPuDOHmDsSwmWuqgrqTCsPZXiOKxvnxAxuxyjvNBdQEM+prcXeEWtn+PxxdvUHiCyUeR7Rdh+xnKna8TMVrtC/qr/7+mc0gpBnO+B0REbHCfWBgeKzX4MlyzmJzDNiB49GkzttX+ZkAJlS4j1OY98AS5GyhaCQaMusn6fUUta5G92+IfCQGZPxahgrQXDVU5POFfBxAxXuoDeCX48CWmBqYyFYXApHR1wYadxbMYlwO2phYXO3PlsT0RXN3daoOXLb+jvpIkKHJrTx17vgYzP4xN6xH2l82sDQdCmVPHrnXg9gu3fHRxS/0LhTA5us5L0NQgJCUP1jJWX1T+a+6OgjH/NMnva6MpelyjRwGrEEWb4Ni2MuQGebmsEpHdsPAOrgyJcJKrIXDJZ1P8WQB+THw3arCbug+EzHMZcPO6+oo62Fs/vXfdvjRWyRpBxQQ00GQBX7AirlZ/AEPD+C+UC2g7jkzcvwBn++R2v8LzL7w=
