resources:
  - tandoor-env.enc.yaml
  - statefulset.yaml
  - service.yaml
  - dnsendpoint.yaml

configMapGenerator:
  - name: tandoor-env
    namespace: medium-place
    env: configuration/tandoor.env
