resources:
  - configuration/tandoor-env.yaml.enc
  - statefulset.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: tandoor-env
    namespace: medium-place
    env: configuration/tandoor.env
