apiVersion: v1
kind: Secret
metadata:
    name: tandoor-env
    namespace: medium-place
data:
    SECRET_KEY: ENC[AES256_GCM,data:f/AlS+RJtvcNr1Bnjtrx0ZqTcFLmoSNrbpCxzGgUU30x0mAeMmxHf95zu/rsoRyUB7goiGPdhpDyt6XRDEz/4g==,iv:AFGV4/kSQm6keUlMTTU+gKso6cY35xnAez/tisvwKPc=,tag:iEObklWpIAlZbpCIAwo5vA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:gJ4E6WFam3HsGLWzFvvCX6mGmj5OBlO7lODABl17AO7fvtIT86L5J6TKsjP/hMGIqvXLSw==,iv:WTl0Av53fKUWNGV6hUC/vGg0rzLvuKaC0y7LYRd4vIg=,tag:4c7ja7MSIl138hKhfiy3mw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:mihKRQnUvMpADAeGzANCeLc3tjPH4A7DU2m+/w==,iv:tUNwZIRKFYwa/iqZUixSVmclQuoIozCjz8fNrN7K5MU=,tag:3OYCGlVuoBYCmeAmUFMseA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bakMc9DiL8zpTuNW3EC6L5vF4BRvkpXo/f+Yyye9FDB1xRyQuu1xe2sGFeYYMvQzx+7FRCDQz3JXX4quBjllxQ==,iv:mSb+YNAoyy4Q1ksM/66KcnbJK/HYBW0NjYrcuDafr0Q=,tag:f+vbV5lN91q30fEp/vEZ2g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:snzhSQKFbzPlN/Ask6rCxyhf+/q5tvoi5Srmvw==,iv:oJdOffnbP5ahlfP8XEy8KT2TAjilS0gMYH/idRE07bM=,tag:RhtRpve5LTa0o2G8Z2Fh7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbldWSnlGaFRYVUVXZnRP
            enZMeTJlRkxXQ3llQjNNMzVCV3lLR2VEMG1ZCk5mWlNMYkxJdUFBNGJQZWZxdGFY
            OExtdFZteWFvWHNIczNYK0p6dW9BNUUKLS0tIFNIQWk1R1hqdUtpampMbWpqT2Zq
            d3ZkekJqOXJtazhaaHZTK3o4R0JVN3cK5IvpL6mVARqC7ZJ1S1NAlh2AJTg8SEFC
            VN/FU5duBYGdStqu+mz3n/7qmM0V+mI1FFO7Qbx+cj1beiYKNd4eFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T21:21:43Z"
    mac: ENC[AES256_GCM,data:Kf10AQNgONm11E3MieKXqSBaT8xG9FhdMI4Mz0KuSjmBpHVEOAxObAlVuU39xj0K8QEH+BDUJSQ3MWmkQYfokRq5THC3cX81XwsxckEqLZRt/p+XvI/6gyCY6/FicQCKauHTdqT1OxzcvFkrO+wYDsLnW7uDOXH6mc7dydeXjBk=,iv:VLOMT3b1TInHd3ZYi7KNtRUTT1H0UaqTPzHSRuPeQC0=,tag:1S05TTqTqXfRwxwJzrUrHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
