apiVersion: v1
kind: Secret
metadata:
    name: fireflyiii-env
    namespace: medium-place
data:
    APP_KEY: ENC[AES256_GCM,data:5xdX30NtXADRaweqQyVNhijwEW/J/F+CoH5mFzFoTgYEpjGH5w54X0kA19Y=,iv:d57H6VsL7+3ILL4NbQRU56nby+Ff3hhb1HhfZkUjHck=,tag:p4aOmNX/Mp7MtYXEFPAUKw==,type:str]
    DB_HOST: ENC[AES256_GCM,data:PzT89+Yg6/sxnmAi6odDubqgP7hVmdKtZvv3MlTv99P+R6ICvV3WI5fiRlaA7eU6W5tvOg==,iv:AO7SwpRjl9RWfLo5SmeMfK9EgjKGGrQX7I471sC4td4=,tag:nNrHYdrGMVUFTS8IXRoatQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:vhq29Rzu4QM=,iv:x0FNTafBHjfNhRPYr020K6xSea+EUr/5qBzx9FxLgvg=,tag:BEJQu1FbmN31wQtEGH5cIQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:A0CAD9lREl2ll54KjX4DvxIwN0/uV8v032n3Fpvil34=,iv:Aucznje11Odwe+8Ns3Q4G2/yunf/JSoMYiLs5JmSER0=,tag:a67X8mOQolJj3FW8lmEnMA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:mTORkfh7LOq85K1wS1KzPZ3947+Gjmh1ZOj3WdxlwNsR/3x/rbrrQ//S1l+jNc8Y14GUlf3PTqZJ9AVsqafOXQ==,iv:PiTKLuASCvkOWbVtLkp/I87dvDfBFVGdPVWcTj/X6Yo=,tag:MyXuQ1T/Zfe3cchTt5og9g==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:I0bxTE2pqicruY51gB/VD2nYMvy0Z1KiA36PzorQcKo=,iv:OgOcBz+eYfLJw84P1S4ekAezQxKzdHv5yeds0wZyAq8=,tag:V9WwH91rNKHqnETAK289rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQzNvTDVJQkZKQk02NS90
            UEtNNGg4WlR1QXFTVmVYRGNGZ0xhMlN4NG44Cms0V3JqWlRSWENoWEo4aGRySmov
            QXB2NitxUzNVeVdGbWVPWnpXWTA4anMKLS0tIFFqbm5uTFBhQWY3c05obXVPR2tk
            aExCUHltanB3U3pzc1ZicWUwTnJLWWcKHv6d1dpuwBGbnqO83BL6JDKMrkEjATj6
            kNpbsVkWmbOhhtWNgYP0M+R/i709IaaKuphkg3YPwLIO8C/uFbz3eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T19:46:23Z"
    mac: ENC[AES256_GCM,data:y33ClnxQoB75sofs8cKv3Dn1w92r2sy0l5TXhHPPaYiQjDi4ugXj3azwm78dohpictBQYS7syQ20Mz57bZo9gtBQB/i9WcwXdsT4KtuBvLw6orSxYQfi/Zd8m43q4j+IRinXnI0f0dE62BYHEns7OA3dYLH7RPAgpnicaUsCZ7A=,iv:BFsXWb8ukYMiHYFs8CICmD8tEWqiNADBPLXsihG0rHE=,tag:Uj9trH1kpsfbx+WIS/Up7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
