apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-env
    namespace: medium-place
data:
    APP_KEY: ENC[AES256_GCM,data:Z3tlcSzlhtJEbsMPaubTOh8OewLBvX1qKuHBiLti5HQOrG6ERFKKp8hig5w=,iv:tl6HXnUmW9x1s8bGhNlXdWgNkVZL1h8sjKx0byTS6tQ=,tag:ihpuK1rCTOUyyXZ4r+LUAg==,type:str]
    DB_HOST: ENC[AES256_GCM,data:2lFr6W8QmFbAubh9vXAqaRX3Fm+yw1la7anFBZZGcROu73iVd02mwG587jlq3WBpCPWqkw==,iv:pOc2JYugIEVbbESViXEcNbw3b3tsUeUMs8lgrgUT/ss=,tag:qJWc9bg5GsGPBiuXkt4J8g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:UxNKa3B+WwI=,iv:ENivcmaBZ/6cuTjKm+H8SX+bn6B+mPrheE5g5BgB7xU=,tag:EE/38UVYQyJ0Vachx3nEdg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:LwAnWDfk4R33PSH4qJG6OAN0jkFgu2UOFSBBGQ42KZY=,iv:pe88UrfmJJ/IXg1Rq2qe+3OVAfnHjMEsm5KyvK7z8r4=,tag:JUeoyGYKX49QRJL3Atap3Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ystdcf+REiDMOqEafPE2xpSjY54+bP6YJOLq01NUBYbEBxa/TCvcMEAdU8EtNnRtYhVwSGJ5By940btSVc0L2g==,iv:vJjVOL2zA/vf+MZtFk6PsD54otmnUDTyyV6q9Ebey+A=,tag:/1G66KVPsLAJ9n+3eIgRPw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:HBXg2eDAMp43uW4XgLs7xEie/mZG9A3YBeeTzVWnzmE=,iv:eeSCTjjvdi/1h3opZbqPaBmryFF03+cYvaCsNKjdmVY=,tag:ouy9HcEF+37p3pKME8+u0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UWJKbWxNUzhqMDY2c1oy
            TGVUV251S29aczl4Z2tQZFdTSml1d0hBNWlVCmlyS2pvY05rZmEzTGRGaHFPTTJ0
            VjM5NExpUDhlR0w0MTJ1TzhVQjVSbWMKLS0tIExEem5QREVTSzVuNDhLTFNsRVBT
            UFlZODNOaDFCR2ZxOUlReHY2SllLSVkKxH8Filf7uKXPPhxf5ktcvBhXc4U4ydZi
            Ve/zebGkRZ9FJA2y34GWtEGFFqbaXYe9xm+26x3wsf6nffrUX0tDdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T19:53:09Z"
    mac: ENC[AES256_GCM,data:5TDOx5D/0fTlrgVu6aMlMtZO1FOkGsmt5CHZkwfE+ZYKezCqpadwsCHIqeMqFq+riwPWN5WSJwLtR/Bh6pil930IM8mi6bgZP0I/vaKT/baRQrBxXsugnnrrgFGipb2dxgwY1yLMVV6YcKqFif8tgcll9oup33qERVskRabmYwc=,iv:EEKpB5apMdGcIi0vxiZSG9x+fk1HDWIeYLz9QOapXDc=,tag:5gH++aAiCBqZlmYt+Ox8Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
