resources:
  - firefly-iii-env.enc.yaml
  - statefulset.yaml
  - cronjob.yaml
  - service.yaml
  - dnsendpoint.yaml

configMapGenerator:
  - name: firefly-iii-env
    namespace: medium-place
    env: configuration/firefly-iii.env
