apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: sealed-secrets-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: sealed-secrets-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-key-admin

subjects:
  - kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: sealed-secrets-service-proxier
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: sealed-secrets-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-service-proxier

subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
