apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: sealed-secrets-key-admin
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: sealed-secrets-controller

rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: sealed-secrets-service-proxier
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: sealed-secrets-controller

rules:
  - apiGroups:
      - ""
    resourceNames:
      - sealed-secrets-controller
    resources:
      - services
    verbs:
      - get

  - apiGroups:
      - ""
    resourceNames:
      - "http:sealed-secrets-controller:"
      - http:sealed-secrets-controller:http
      - sealed-secrets-controller
    resources:
      - services/proxy
    verbs:
      - create
      - get
