apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-ingress-controller-config
  namespace: nginx-ingress-controller

data:
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-ingress-controller-tcp-services
  namespace: nginx-ingress-controller

data:
  "22": "medium-place/gitea:22"

