apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
  labels:
    app.kubernetes.io/part-of: nginx-ingress-controller

rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get

  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - endpoints
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - update
      - watch

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses/status
    verbs:
      - update

  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - ingress-controller-leader
    verbs:
      - get
      - update

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create

  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - update

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
