apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: mastodon
  namespace: medium-place
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: 100
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app.kubernetes.io/part-of: mastodon

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - plaza.medium.place
      secretName: plaza.medium.place-tls

  rules:
    - host: plaza.medium.place
      http:
        paths:
          - pathType: Prefix
            path: /api/v1/streaming
            backend:
              service:
                name: mastodon
                port:
                  name: http-ws
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mastodon
                port:
                  name: http
