resources:
  - configuration/mastodon-env.yaml.enc
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: mastodon-env
    namespace: medium-place
    env: configuration/mastodon.env
