apiVersion: v1
kind: Service

metadata:
  name: mastodon-web
  namespace: medium-place
  labels:
    app.kubernetes.io/name: mastodon-web
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: 4.0.2

spec:
  selector:
    app.kubernetes.io/name: mastodon-web
    app.kubernetes.io/part-of: mastodon

  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service

metadata:
  name: mastodon-streaming
  namespace: medium-place
  labels:
    app.kubernetes.io/name: mastodon-streaming
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: 4.0.2

spec:
  selector:
    app.kubernetes.io/name: mastodon-streaming
    app.kubernetes.io/part-of: mastodon

  ports:
    - name: http-ws
      protocol: TCP
      port: 4000
      targetPort: http-ws
