apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-private
  namespace: contour-private

spec:
  interval: 1m

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 10.0.0

  values:
    contour:
      # We are deploying Contour twice - having both deployments manage the CRDs
      # fails. We will let the `contour-public` deployment handle these.
      manageCRDs: false
      ingressClass:
        name: private
        default: true
    envoy:
      useHostPort: false
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
        clusterIP: 10.96.0.60
