apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: contour-private
  namespace: contour-private

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false

  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 9.1.6

  values:
    contour:
      # We are deploying Contour twice - having both deployments manage the CRDs 
      # fails. We will let the `contour-public` deployment handle these.
      manageCRDs: false
      ingressClass:
        name: private
        default: true
    envoy:
      service:
        type: ClusterIP
        externalTrafficPolicy: ""
        clusterIP: 10.96.0.60

 
