apiVersion: apps/v1
kind: Deployment

metadata:
  name: external-dns
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/version: 0.12.2

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/part-of: external-dns

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/part-of: external-dns
        app.kubernetes.io/version: 0.12.2

    spec:
      serviceAccountName: external-dns

      terminationGracePeriodSeconds: 50

      containers:
        - name: external-dns

          imagePullPolicy: Always
          image: bitnami/external-dns:0.12.2
          args:
            - --provider=cloudflare
            - --policy=upsert-only
            - --registry=txt
            - --txt-prefix=external-dns.
            - --txt-owner-id=nutria
            - --source=service
            - --source=ingress
            - --source=crd
            - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
            - --crd-source-kind=DNSEndpoint
            - --interval=30s

          envFrom:
            - secretRef:
                name: external-dns-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 7979

          livenessProbe:
            httpGet:
              scheme: HTTP
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: http
              path: /healthz
