kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: external-dns-env
  namespace: external-dns
  creationTimestamp: null
spec:
  template:
    metadata:
      name: external-dns-env
      namespace: external-dns
      creationTimestamp: null
    data: null
  encryptedData:
    CF_API_TOKEN: AgBpeSQzOOg21fSfn7fiwI5Su4FxyULrARCjWbimMPlaZhuOWvVm7xZqu34QEVEQ9uLCWMKojiPVs1vqn1YhpODYkqHusK24VhFznOzlAeGpoBYO9Cdmt33ER1pyGgLtzT1XpV4rATDIshRCl3A5tq9pFsFpS2kleeTYCXpXuNIe2d8xEYTLZOTm01/HjJBUvMxg/O8ECp8w27Af6qtyCycu7GcqKLJU7qtiY9m8uhdcWXFE5gxWyPIwz3YdUq3b4ceNr7vZ6sNkrZSNmu2/oAjZIJKuBZf3QbfyylgXfA5VU/DVCVyBttaC3jxh1n0Iskl+SU6Ue2tSwhVN0ypro0DKhjadEp5Rwq48TfNRBUJmkvKWJKQ4Z4HoH2cxUplJO2ba/41j2ekkgqu6YPGSfU7rC0o1ItHdBHKai2i7JZu/lpZfgPGhgLbUtqcABUDCJIca027ffY/s7iFOES7kVIpy220gLFgj+P8Bhfix396wPAUD0ZJ6HCM2wHkpq49oX+FtBqGxYnkJTP2kg2O9MCF4vg2cmetIbsgd6eie56Q/FZ7DcT1UbXUDi7Mb4oj3SiOBPKk4T+83JGEkI7ug283RYGYcXQIIeAhX+g5Y5gX4OUVAI8A/ifs5TrUNbaWg8K6y+l64wXAYicnUtCKfA852wmIz9bk5JQkCP5ev/NTnkn9P22M/dwwpcwo2orJvhbm9K4gm+FjH7Cd+ltWBwbmmfiePXqAsp4KrLOo5UA4zZv+KQdUeIMIF
