apiVersion: apps/v1
kind: Deployment

metadata:
  name: synapse-facebook-bridge 
  namespace: medium-place
  labels:
    app.kubernetes.io/name: facebook-bridge
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/version: 0.4.0

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: facebook-bridge
      app.kubernetes.io/part-of: synapse

  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: facebook-bridge
        app.kubernetes.io/part-of: synapse
        app.kubernetes.io/version: 0.4.0  

    spec:
      volumes:
        - name: synapse-facebook-bridge-config
          secret:
            secretName: synapse-facebook-bridge-config
        - name: synapse-bridge-registration
          secret:
            secretName: synapse-bridge-registration

      containers:
        - name: mautrix-facebook 
          image: dock.mau.dev/mautrix/facebook:v0.4.0

          volumeMounts:
            - name: synapse-facebook-bridge-config
              mountPath: /data/config.yaml
              subPath: config.yaml
              readOnly: false
            - name: synapse-bridge-registration
              mountPath: /data/registration.yaml
              subPath: facebook.yaml
              readOnly: false

          ports:
            - name: http
              protocol: TCP
              containerPort: 29319
