apiVersion: v1
kind: Service

metadata:
  name: synapse-facebook-bridge
  namespace: medium-place
  labels:
    app.kubernetes.io/name: facebook-bridge
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/version: 0.4.0

spec:
  selector:
    app.kubernetes.io/name: facebook-bridge
    app.kubernetes.io/part-of: synapse

  ports:
    - name: http
      protocol: TCP
      port: 29319
      targetPort: http
