resources:
  - vikunja-backend-env.enc.yaml
  - statefulset.yaml
  - service.yaml

configMapGenerator:
  - name: vikunja-backend-env
    namespace: medium-place
    env: configuration/vikunja-backend.env
