apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: vikunja-backend
  namespace: medium-place
  labels:
    app.kubernetes.io/name: vikunja-backend
    app.kubernetes.io/part-of: vikunja
    app.kubernetes.io/version: 0.18.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: vikunja-backend
      app.kubernetes.io/part-of: vikunja

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: vikunja-backend
        app.kubernetes.io/part-of: vikunja
        app.kubernetes.io/version: 0.18.1

    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: vikunja-backend
          image: vikunja/api:0.18.1

          volumeMounts:
            - name: data
              mountPath: /app/vikunja/files

          envFrom:
            - configMapRef:
                name: vikunja-backend-env
            - secretRef:
                name: vikunja-backend-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 3456

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
