apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-env
    namespace: leuchtturm-io
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:xaURMV1rw+3RtXe1lkipUPvYBVu4Rkbc9EfG8jNdzzi4aFsdus4LtoLGg9gbor6QhcWR/euhHDgeiizaC9xb0Q==,iv:DoHmxyV1ZzYiQe1pZKmwgteJaA8RqjiZcS4nMbtyEV0=,tag:HRpO1hgcDObYJjxOfyieTQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:b1QvCLXea73Up1/zbDW42oQL/vo4JQJlgC90NjOFSu5EQlJtl7IpnjM5MdqOIwPNxJ3ngbQFHKx6m2StknDTGPSjVG7bJXQEdaITiyfG0PLFkZ2rP1ailC0n7Ye0IjmVkT6dL88DUNPozvyTrYfyRPlzspVY+BruictlWse9W40yXv/kscIxy/4gK5EcHntGidZADDj4I8y9Q+bju3UwvCzM2O1fcQN1ZcxgDFIFVAvCPgUJLaJ90eMZHCXpJF/KFq2t5hgHsTt28abrd6pD/g==,iv:leM4XumHvlGks3ZELsS7LyzOYYbMwNFgSF+PTNnC8Oc=,tag:UyHgRfdqjDvfs+HNNnfDIA==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:BUR3TVJeALnEIMACS2G2Q3W0hxMORCaSCO4YWqPnUCSrJQyp,iv:IA50CU6h/09udJ9bgGBH5NrjH5K8Xrxf3M2WNqx5NXw=,tag:EqtUkEPTyRbH1R+Y1IWATw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:8BIcI24uh+9uZdj6LFEhGGXtJ9AMCnBVvcSRFsVdZeo=,iv:fRWf9eJ4KQSEFPUCyexvWpNDTO6DWHoetACCVZg107I=,tag:uZtL+Iq23NNZAgq1dfv4tg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:l0EMP0O+FtSFHEj8khzhOhXp6yFb+lARnJdv8dGvFUTbXm7+nkqapvwoYQb6+nZxcOk5oMqDi2KdSCH+5cYUjXw3k0M9HWek9VITdluSCGoUgUKYLWQKqQ==,iv:eVzPZ2zwoY2feSBHmh6oTX4LSAHPoWZveEd0rsHpHrI=,tag:WYsC79UocA9xbQE1m6Jalw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:5zMxZleanhO21cLNOq+yvqeWn+M55C63oQ8N9YLt8Yc=,iv:vRJrwNfv64ZYyfbVp7AQulsJxku8GumkjZtNibBtHu4=,tag:u35bS9lo2Gq/Y7PZeEzJBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERjl6OWxmZFlNbmVOaDE3
            Tk94WkhIMFFMaGtXS29GMU5UK0tEQnVCZEhBCkkrbFFYVlBCcjBHdnkxTXZNa1FX
            M08xMCtHRjRxMUhTM0FETW1WdlF6cXcKLS0tIHhqOGlNYyt0UWJ2azN3aDhKM0sx
            OEFzWFk4S2I5ZnkvQWhlTEp2Q3JCbU0KO11EO1YZ9VW3mhx1f7Cns6gDTZkZ950S
            xY97LdwNhXjhTCHmVtH/rHuwQ3+9iMi32hHJGKfvabW0wpC5GIDcSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T20:37:42Z"
    mac: ENC[AES256_GCM,data:WKi59GdPE6+fOltLLQydTZ6oVturhTwSdMhizPQH96+w3shyB3iE4SqauksunWTnal6HWFjKVqZwi0m4x6ekbLtJpFNQvBxKzsVoCJ87QF/Xhr5FaS4m6RAa2yoBYN+qFvO+Iq0BGVNtyWRpwHrjKI/f26Y91kOFaOqGzGgpE+k=,iv:rIQTJ+QjuogfRkSehE+wL/iBaG0XYmzOBEtA+aE3Rhs=,tag:Uu1hviWw4fumpV3FrZzcCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
