apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-env
    namespace: leuchtturm-io
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:egUlhWU+8UUBlJVnP0RtW0mVHWCcNjeu5wziuEhBD5XAFtvtg/qpoT0xDtNobGqFCAjHVYMR0hv8swFfV+aAXA==,iv:/z+FIf8nysAV7r5LEKCDBkjQhGkxWmlEYG7eYBhQAho=,tag:2Dah3rpz87SGnjAxFXJhqQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:33vITNRMRFO4KwkDxEZdYiOs4vjrEOGD7rQ+mq6md3cHs4cButGoPM2hR3cVkIsPb6v2OdUpy+EmcWPMTwA+no7dwvEk4KpHTpde8Y0iX4mFFmSYoeH3JgChDTfuEFwFIjj0ikufxur/U6BPFiSF+aDkjZtSX9P5+D7KxREKgj+kNxQkY+lEzDgoEIz/AEjAOEhtm7+Du/6K7q5bRP+nyJ9We6/uEe+Ox7aNteByzb0RKQPfxp/Hr3egHbUpt0yUvjzwMrAdIhbSfUj8k7NR2w==,iv:ZodCMK5lvEUYYSaksZTaEIRGO6BdJV7iFNHGHarzazI=,tag:dv0Oax6g8mI7FPxSLxnXFQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:hM9P1hCDzBzsrI/Iw2GwBeSqUrjeDU2qX1DIioXViLnZ41Pd,iv:HpxqluFu6/aPUXzNgZ8xB0GmSJk0vzNiEJMLa88LHgs=,tag:2IE1MIwSuSqZuecaKwkGyQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:qMB6XR6wh5DgHx8ru++lwn/IfOUEhqzAbvOJwBdIF8Y=,iv:jcC9LAymduLVC9uPVnGbAZe2m08UOmmTatT1wEUMrnU=,tag:zEUM0RkklaCpGNsdGpLnlQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:LNNMWElPOK2Jzdi6UXnxri/9ckCvsdM/jj75xJVn2HR/kUjfKR90QK+wOne9o54KfGN/vtLdvu2g0MDYcEkTibMEbIfQRFjIQA6C+Pomy73CEkHxjYuMBA==,iv:ZKcyCOREyaabW8hDJQpeLQF0yz2TGh8dcQ65BZKotOU=,tag:DnQkEgOxYUz3EmUtsS7vHA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:8bN4B3PjmvP2UZvqKZSp4cKTGBvWbm8JLaxpGj2LoT8=,iv:k7Ml8Cib7rQLuy98zotJ/eaL4aLzQ3YCqXWsny7b1bM=,tag:hEyoxZq26ukkpGr+FBtN1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WUVIT1A0U3Zra1VxRXVa
            eS9oNE5renRwMkNFYUplQjlNMzJWY2Z2MjFBCmtDTVFvSURBSTFxR05XV0dsUkE3
            ZUdPRnpjcmdQclBacjlMeEx0YTVXaWcKLS0tIHh1WWprM2FKM1AwQXVXWTA4bVJ5
            VVdEQlJyV01TMjBvVVg5K1gvM0NzSXcKbWcJGLhSFJEP6GZgG2fmD+27mYZEW+c0
            bjVqE6gHhMwAVOo4Gm0m42DRjTXGRada4rI3iJdu+gE/FaZ4C+SAhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T21:21:43Z"
    mac: ENC[AES256_GCM,data:XmVCDcx55y+gFNCxSraiQynO/BCFbABm7uUaoCu9N95m1CLV/fHcy/6imQSlrz1Hp6AF9n72FlFveR1eioFntTRRcbjIDBqvIyiEe94qWqwS0b0UzMbjGRtLr7LY4xelpcIONbTiO9SuPMtygT4jlp3SGdQBJ1ZgoFEMZCYPTo4=,iv:nHgan+9P+TFchCWAJ69HXg7NUQhklZZhxkP5XMIU1MY=,tag:2Az4AhKMP3bSyQh/dRA4ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
