apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: tailscale
  namespace: tailscale
  labels:
    app.kubernetes.io/part-of: tailscale

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tailscale

subjects:
- kind: ServiceAccount
  namespace: tailscale
  name: tailscale

