apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: caddy
  namespace: tailscale
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/part-of: tailscale
    app.kubernetes.io/version: 2.6.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
      app.kubernetes.io/part-of: tailscale

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: caddy
        app.kubernetes.io/part-of: tailscale
        app.kubernetes.io/version: 2.6.1

    spec:
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config

      containers:
        - name: caddy
          image: slothcroissant/caddy-cloudflaredns:2.6.1

          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
            - name: data 
              mountPath: /data

          envFrom:
            - secretRef:
                name: caddy-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: https
              protocol: TCP 
              containerPort: 443

  volumeClaimTemplates:
    - metadata:
        name: data

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
