apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
data:
    TS_AUTH_KEY: ENC[AES256_GCM,data:vs26xYhsf9kFvzWDAy53EqgDZLcnuq/JgcGgdlObmR+P1JwPJgmMMTNXqkuu0bDhRT/0JbAxKwOA86MSqhQpFObojL476nT+zpjzpQ==,iv:2eckbhBjKFJ/WhYTU4271YURsBuraWaLJkG8uBht4Lc=,tag:oC/XQzKcUf8hMWB6kpKOqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdEh6OWthcGVLb0MyVTVn
            U25oYzhYYWp2Z2JIWGJXRGIwdjFlV2dDRXhVCk5PWnZoc1g4YVptRW54QkJ3TVdU
            SDkrY0UvNTFJTWxzelBiS2k3OE1SZEkKLS0tIGsvbUVvWk0rQ3VsbWZNczg3MGVv
            dGkyQnF0cVhWa0Q0KzlOTDRCekFORzQK1pIzXhoocL6YqUIEsxHJRz1ysBALLXgO
            v7BzLA4/M/ESelTNLdj4m23RITBekN+fEG2rvzldqJVneySVGMeFXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T14:35:19Z"
    mac: ENC[AES256_GCM,data:T49HuyNiplclQYQSimVUA8biXYuR+MQQDT1CNKb7HjPi9UASPNpR7y//9d8PqXri/BQ3LE+sOBDyRYp4ASWUELe2Vlt+45qcvis+E3NHgIhJs6d0jqeFAXhvJvnBwRjUrzOt/t5r1+g/KKk7WMSbOhWE06d5MbFyb60qsEIgVZw=,iv:+C3f7NouhHKnuvUCGhzcopo9BeqZaK59AVkvqdtEMJs=,tag:WQhjwpXovetUEevYh+tDnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
