apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: diun
  labels:
    app.kubernetes.io/part-of: diun

rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
