apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - statefulset.yaml

generatorOptions:
  labels:
    app.kubernetes.io/part-of: diun
configMapGenerator:
  - name: diun-config
    namespace: diun
    files:
      - configuration/images.yaml
