kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: diun-env
  namespace: diun
  creationTimestamp: null
spec:
  template:
    metadata:
      name: diun-env
      namespace: diun
      creationTimestamp: null
    data: null
  encryptedData:
    DIUN_REGOPTS_DOCKERIO_PASSWORD: AgCTDl3p/OcnA5dyt4TVivXotbJZwGWpEmvk2ZQscV01IjORX33rVEYzVycwKrk4f4UX4tRMasJzTFuGuaRUSSGNidS/GNhb1THHwo77Xk3QkdsbRZXtZajSd86I7bI1PHhqwsO45zwEDC7hPamruEhpUMK2nj/6GP3oX3pw4HdO98ByaIKWRMpKhh/siXLO2ltGTq4mZseCG7URdJQg09/qKg/IMe9w+Ul8Zy+00zK6rf/Qc+EAn6Lr3umTkWaMlC5JApKMSLC4kb2P8Q85enznVzr4qiO11zvsQ0FJ26he2FKi1MtajOfM4CoYQvzZcv/9eYZVxbUqj/GUWkKyFj0NIVlD1zsO1ZVi2Vg1mJcEhc2+ZF3iDvGgFk74hyx/7efRoI6lu6E0G72u7hrqtk1AW+2J8DuSfchG84qM9xMp9tyZcjfNBRjBwvLdG6J44z1HRJDdsGY8Zk+/mWqsZusUqDwnNSSa2lfYee69wPhjLRz+3a3HHAOsGtOK81+nW/QVE+qyXKGPRr0E/+4ANBbTNH0JxSmGT2MqzG2pc1NI1r/CqCZq/g1iPtQ1CHEkCLcnxHN2gn52RGQEYQZvznckSUM9kKgNw2aakU4mib83KH9jAjj5ZZz6kBrp0DBDZeu9v2gGtjEML2/nA+43Jwb0phB0iKJwrOtiLZ3U+oI+2aKrv0rE4AuDo6ZEO0ZOUbvgQvIn2yQLFw2zffyccDhE+eqwUDGsyVOhAgBlTE/63A==
    DIUN_REGOPTS_DOCKERIO_USERNAME: AgALlQr3NKzkJ1vNbnW3oKi8RcmCj16ievUv0DSZvP3WSIHXpUZ4IBuGnAegAbR4GjMq+JOe8MH9YZi9Ab+Kv4t4EwKYJ6ghR/Glsc5NjmstPnSpVoOXKy//Am7fifO9RMJGmUpQp7uxfbKHoypb+FRLD2Ylh1c8cXtjPnYvfRcV7JyhEBAPXjrDvPg2wG4W6Il3jeHw08NI+f255FRrIAXFBKZdsrU6V4O79l9lxRrDuRkWZakUUZCEeLNG61qkI0UyA6LCKgertLXDpPByT7CixbFTgcch8JGq3o2A0UPHLui5ghW9h0cY4N2HvSv2/VtP/21wxuzxfPFhYI9osfSxVHnB48eL9GQymcdkP24c7FCrqC31PdtBy6UlwFmpb0eVOuvxUoRJbG44khkim05qVLF+nz4H9eNXpvD6VAtrWuqW/aJXUaW3t8eoINgmivm2Kbw2sLVrFHjiYF/qOM/AyM+DWMLYUQncsCK2CfuYYzX4C2RDeFeKIwa21hYI32cslhcTYqXnCuavKGvPg5x6TVXH910sTzlxoZgr1MwkBdkjYc8oFWaWNBH09jch9wMn7KXdIHorvwZ4QLbrQcue5m57i9p9MrE1xXqCH72pkEiB6Nv9cye9YdjkldyisPT8cGnVnCZdZz1QQtDacN0Q7zmIlh0GoqOpSx0HIZZwPQo4Gc/EdtJoULHltzAjRHRna3S09jqoamnWIQrhc+I=
