apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: synapse
  namespace: medium-place
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: true
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: synapse

spec:
  ingressClassName: public

  tls:
    - hosts:
        - synapse.medium.place
      secretName: synapse.medium.place-tls

  rules:
    - host: synapse.medium.place
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: synapse
                port:
                  name: http
