{{- $userName := default (include "base.fullname" . | trim | snakecase) .Values.authentication.applicationUser.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . | trim }}-init-scripts
data:
  setup_wal_g.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
      ALTER SYSTEM SET archive_mode=on;
      ALTER SYSTEM SET archive_timeout=60;
      ALTER SYSTEM SET archive_command='/wal-g wal-push %p';
      ALTER SYSTEM SET restore_command='/wal-g wal-fetch %f %p';
    EOSQL

  setup_databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
      CREATE USER {{ $userName }} WITH PASSWORD '${{ $userName | upper }}_PASSWORD';
      {{ range .Values.databases }}
      CREATE DATABASE {{ . }};
      GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO {{ $userName }};
      {{ end }}
    EOSQL
    {{ range .Values.databases }}
    psql -v ON_ERROR_STOP=1 --username postgres --dbname "{{ . }}" <<-EOSQL
      CREATE SCHEMA AUTHORIZATION {{ $userName }};
    EOSQL
    {{ end }}

