{{- $userName := default (include "base.fullname" . | trim | snakecase) .Values.authentication.applicationUser.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base.fullname" . | trim }}-postgresql-init-scripts
data:
  setup.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      CREATE USER {{ $userName }} WITH PASSWORD '${{ $userName | upper }}_PASSWORD';
      {{ range .Values.databases }}
      CREATE DATABASE {{ . }};
      GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO {{ $userName }};
      {{ end }}
    EOSQL
    {{ range .Values.databases }}
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "{{ . }}" <<-EOSQL
      CREATE SCHEMA {{ include "base.fullname" . | trim | snakecase }} AUTHORIZATION {{ $userName }};
    EOSQL
    {{ end }}

