apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "base.fullname" . | trim }}-postgresql
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ default "10Gi" .Values.persistence.volumeSize }}
  template:
    metadata:
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "base.fullname" . | trim }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ include "base.fullname" . | trim }}-postgresql-init-scripts
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}.:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d



