apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-postgres
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ default "10Gi" .Values.persistence.volumeSize }}
  template:
    metadata:
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "base.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: postgres:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}



