apiVersion: apps/v1
kind: Deployment

metadata:
  name: searxng
  namespace: medium-place
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: searxng
    app.kubernetes.io/version: 2022.08.13

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: searxng
      app.kubernetes.io/part-of: searxng

  template:
    metadata:
      labels:
        app.kubernetes.io/name: searxng
        app.kubernetes.io/part-of: searxng
        app.kubernetes.io/version: 2022.08.13

    spec:
      terminationGracePeriodSeconds: 60

      volumes:
        - name: searxng-config
          secret:
            secretName: searxng-config

      containers:
        - name: searxng
          image: searxng/searxng:2022.08.13-00431906

          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml

          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
