resources:
  - searxng-config.enc.yaml
  - deployment.yaml
  - service.yaml
  - dnsendpoint.yaml

configMapGenerator:
  - name: searxng-env
    namespace: medium-place
    env: configuration/searxng.env
