apiVersion: v1
kind: Secret
metadata:
    name: searxng-config
    namespace: medium-place
data:
    settings.yml: ENC[AES256_GCM,data:iXr1AyiF0QTh6phPo4o8wu/n7Z7z4/wJ010DHx70gCEP34CEcrJv/hUT2/MQydfEfO60UbqeTsLpY0pziK9OMUQSUMPASTBqdO6jjA67eaToeIs292OGzPMOm+dQ+e1iOCWo3a8t0S22rDUHDzzdU+2eL9+Ayzs5MjKP7sAglzLqiRyCmP3kp0+nPPM4hLCsvW5P3I/ebNlh1img6I6uvWKVNpQJG3U551m4L/RooOpXBFwKCTPmj+FqC9GqeWRSzZ0qzsa/PQCbUyumSJGfNy7P9JVhwnM4GfIv4YGVi6JhP/32qGRX2JsC0i4lFZxbahbaVl0dVprwCtwmPHKLoz/ZR7bEwM18pW8KJhckJ/6xdWooa6ePHDonXgYJVA3OIKTIzyy4ZXn+eP8XlRXRax5jbP5wzme1KT/lw2Ix4eR67LQkLpqDrwpjozsQ+Xjz0ITNzNJmqdQ=,iv:geDsIE8AlrCOtoX2xVauGYqEOUYBpPkHWuGYmmYCfUE=,tag:AgFxAJss4dnRZn34pKDeqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q3FJQlc2Q1o4MFA0Q1RZ
            RW9xbklGaTZpSkI4ZllGa2ZQVXlaWVhkSnlJCkIwblZsRFcyalMyM0dlR2E0UDhw
            VTY5dG5JVkJwRnVBZGFxOExJMDBVMEkKLS0tIHVudUpQelZIZGt2cFplTHhJWnFU
            SkxSdlJVdUJuNG1oSkJtdndCcnErY2sKmZyyRlhrP57FQWoPMmtDlpdkZCa36k9h
            HIKpMr2YyAvfUuCQ1OqR3OA/3mSpCUIg4C8wUSws8Ly3hBBoIPOSzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T20:26:04Z"
    mac: ENC[AES256_GCM,data:eio4giDpaiWaonKRsaSOD3ulgWeDsMS5EzyvU6mMQsqMZ2ixKh5RXyTq/C72Xsr6fL9iQfnM+Vw/EkjD3sRjOzMW0qxihvjYqykN84XrhF5rDvi9A896GGUG/W4s+6g/Jhgl6qfTtKmAR8xs7TLmnZgPpNYtaV+S/UF7p05v2fI=,iv:p73XVAf4ae5dcKGEyX3pgjuimNqsDm/IOUgHCA0OXP4=,tag:fLDPWhoDMM99JXmkxrmB7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
