apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: woodpecker-server
  namespace: medium-place

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: true
    cleanupOnFail: false

  chart:
    spec:
      chart: woodpecker-server
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      version: 0.15.5

  values:
    env:
    extraSecretNamesForEnvFrom:
      - woodpecker-env
    persistentVolume:
      storageClass: hcloud-volume
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: nutria.tail9b5a.ts.net
      tls:
        - hosts:
            - ci.medium.place
          secretName: ci.medium.place-tls
      hosts:
        - host: ci.medium.place
          paths:
            - path: /
              backend:
                serviceName: medium-place-woodpecker
                servicePort: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: woodpecker-agent
  namespace: medium-place

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: true
    cleanupOnFail: false

  chart:
    spec:
      chart: woodpecker-agent
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      version: 0.15.5

  values:
    env:
    extraSecretNamesForEnvFrom:
      - woodpecker-env
