apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: woodpecker-server
  namespace: woodpecker

spec:
  interval: 1m

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false

  chart:
    spec:
      chart: woodpecker-server
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
      version: 0.15.5

  values:

