resources:
  - configuration/gitea-env.yaml.enc
  - statefulset.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: gitea-env
    namespace: medium-place
    env: configuration/gitea.env
