apiVersion: v1
kind: Service

metadata:
  name: paperless-ngx-tika
  namespace: medium-place
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: 2.1.0

spec:
  selector:
    app.kubernetes.io/name: tika
    app.kubernetes.io/part-of: paperless-ngx

  ports:
    - name: tika
      protocol: TCP
      port: 9998
      targetPort: tika
