apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: nginx-ingress-controller
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./workloads/nginx-ingress-controller"
  interval: 60m
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: true
