{{- if (default false .Values.persistence.enabled) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: {{ default "10Gi" .Values.persistence.volumeSize }}
  template:
    metadata:
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "base.fullname" . }}
      containers:
        - name: {{ .Resource.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              protocol: {{ default "TCP" .protocol }}
              containerPort: {{ .port }}
            {{- end }}
          envFrom:
          - secretRef:
              name: {{ .Values.envSecretName }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- end }}
