image:
  tag: 15.0-alpine
  pullPolicy: IfNotPresent

secretName: 

persistence:
  volumeSize: 10Gi

authentication:
  applicationUser:
    # This by convention expects an environment variable with name $NAME_PASSWORD.
    # For example, if the name was set as medium_place_forge here, the environment variable would
    # be $MEDIUM_PLACE_FORGE_PASSWORD.
    name: 

databases:
  # -  
