apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease

metadata:
  name: forge
  namespace: medium-place

spec:
  interval: 1m

  chart:
    spec:
      chart: ./charts/gitea
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: ~0.1.2

  values:
    ingress:
      host: forge2.medium.place
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: http

  upgrade:
    remediation:
      retries: 5

  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  
