apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: medium-place-woodpecker
  namespace: flux-system

spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./workloads/medium-place/woodpecker"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
