apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mastodon-postgresql
  namespace: medium-place
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: "15.1"

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: mastodon

  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/version: "15.1"

    spec:
      terminationGracePeriodSeconds: 60

      securityContext:
        fsGroup: 1001

      containers:
        - name: postgresql

          imagePullPolicy: Always
          image: cschmatzler/postgresql-wal-g:15.1-2.0.1

          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql/data

          envFrom:
            - secretRef:
                name: mastodon-postgresql-env

          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
