apiVersion: v1
kind: Secret
metadata:
    name: mastodon-redis-env
    namespace: medium-place
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:1Ptmaf0PVcsuld1FBwu559KQO1nya6zvxfXPsC7LDaFjHI+PwcYUyMtLxNNCK/crruH4zqeYPzpMSYh/MFA5rg==,iv:X67rEktzz70X2Sc8dcMvVS77+oYXR1lMjYIF6ezJnuw=,tag:oazG0hEQxdBHatz8w0RyDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRmRQd0xmdElSbEZtT0Vy
            cStwWkxmOU1DN0VNTVg2d2JEN2NHYmhpQXdzClFjczJRSVkxUDlHNkU4WVExckQ4
            eWpqaHpyMnhxK3VFekVEdHVzbTl2RkkKLS0tIDF4Tm1KdFFxRnlCUGJYeUpzUXo1
            RGs5SEl0REtuZTFGSXF6NWZKaTdVc2cKgWPpmRVuB+P3w8CX2QXVM2oy5IRDw64v
            9qPTyzsw67EZLu3bh9zTL+e4epNWEqgmmTeV5j4PNpDOeQZFiRTgIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-23T00:03:59Z"
    mac: ENC[AES256_GCM,data:Zjw+waUA4Yvb2zanEf/mSglKRjP1XVgV3tOORFPjQpE2Md3y7gfN/NhaxFLZN0Hq0C9XWCdt+HiIZX+RIk4RYHRC0XnbGg/KDCOG85Q3eivQAcYJwy2nJiq0jU0g63DIpGp7EdydBntnaVweQo0kdivNruRS0QuAkWHFsp3z2jg=,iv:hokuTPwPar7pI2O6T8dj54IbEiWvAkE3jF/8c6zLEVw=,tag:3D2TezSDt4YT05u+0KJORg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
