apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mastodon-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: 6.2.7

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: mastodon

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+-debian-\\d+-r\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/version: 6.2.7

    spec:
      serviceAccountName: mastodon-redis

      terminationGracePeriodSeconds: 60

      securityContext:
        fsGroup: 1001

      containers:
        - name: redis
          image: bitnami/redis:6.2.7-debian-10-r27

          volumeMounts:
            - name: data
              mountPath: /bitnami/redis/data

          envFrom:
            - secretRef:
                name: mastodon-redis-env

          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379

          resources:
            requests:
              cpu: 16m
              memory: 16Mi
            limits:
              cpu: 32m
              memory: 32Mi

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
