apiVersion: apps/v1
kind: Deployment

metadata:
  name: stolon-sentinel
  namespace: stolon
  labels:
    app.kubernetes.io/name: stolon-sentinel
    app.kubernetes.io/part-of: stolon
    app.kubernetes.io/version: 0.17.0

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: stolon-sentinel
      app.kubernetes.io/part-of: stolon

  template:
    metadata:
      labels:
        app.kubernetes.io/name: stolon-sentinel
        app.kubernetes.io/part-of: stolon
        app.kubernetes.io/version: 0.17.0
        stolon-cluster: nutria
        component: stolon-sentinel

    spec:
      serviceAccountName: stolon-sentinel

      terminationGracePeriodSeconds: 60

      containers:
        - name: stolon-sentinel

          image: cschmatzler/stolon:0.17.0-pg14-r1
          command:
            - "/bin/bash"
            - "-ec"
            - "exec gosu stolon stolon-sentinel"

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STSENTINEL_CLUSTER_NAME
              value: nutria
            - name: STSENTINEL_STORE_BACKEND
              value: kubernetes
            - name: STSENTINEL_KUBE_NAMESPACE
              value: stolon
            - name: STSENTINEL_KUBE_RESOURCE_KIND
              value: configmap

          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
