apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: pixelfed
  namespace: medium-place
  labels:
    app.kubernetes.io/name: pixelfed
    app.kubernetes.io/part-of: pixelfed
    app.kubernetes.io/version: 0.11.4

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: pixelfed
      app.kubernetes.io/part-of: pixelfed

  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
      labels:
        app.kubernetes.io/name: pixelfed
        app.kubernetes.io/part-of: pixelfed
        app.kubernetes.io/version: 0.11.4

    spec:
      containers:
        - name: pixelfed

          image: forge.medium.place/nutria/pixelfed:0.11.4
          imagePullSecrets:
            - name: forge

          volumeMounts:
            - name: data
              mountPath: /data

          envFrom:
            - configMapRef:
                name: pixelfed-env
            - secretRef:
                name: pixelfed-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 3000

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place

      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
