apiVersion: apps/v1
kind: Deployment

metadata:
  name: teslamate
  namespace: medium-place
  labels:
    app.kubernetes.io/name: teslamate
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/version: 1.27.0

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: teslamate
      app.kubernetes.io/part-of: teslamate

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+$"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: teslamate
        app.kubernetes.io/part-of: teslamate
        app.kubernetes.io/version: 1.27.0

    spec:
      containers:
        - name: teslamate
          image: teslamate/teslamate:1.27.0

          env:
            - name: DISABLE_MQTT
              value: "true"
          envFrom:
            - secretRef:
                name: teslamate-env

          ports:
            - name: http
              protocol: TCP
              containerPort: 4000
