apiVersion: v1
kind: Service

metadata:
  name: teslamate
  namespace: medium-place
  labels:
    app.kubernetes.io/name: teslamate
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/version: 1.27.1

spec:
  selector:
    app.kubernetes.io/name: teslamate
    app.kubernetes.io/part-of: teslamate

  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: http
