apiVersion: v1
kind: Secret
metadata:
    name: teslamate-env
    namespace: medium-place
data:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:UYAqMvROrrQdJoEUp628Jx4utGtw+Pqxb1FeLv2E41YnHQNojbg9vANXq88=,iv:SSNSk47gWgNPRmewIpHQ4xcGbSlWV/hKTfOt7jdttho=,tag:ttNY5wblGYaKEejE/uibBQ==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:/Dyf+DXKo1BrPl6mGGfnfiIAiXYdF5aco6r9cfY+A/TEb/zUAtx44Ve38iJ76OCmfj6MGg==,iv:Dks21S9dyHo1I+SU4hkQEAayiiThfGGt1o+ajVamJbE=,tag:7Kp0e2/BxFiEELlBBYKtbg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:YHs/lHuLTW3vHWJFr0smQnlFNX3z5grEyMq46rU74V8=,iv:T1RIs+EBGs8q4lIGgorCVrVCGNpOuPkHhPVpmM3meZ0=,tag:IPJ5UYFGEKOOPI2D7rW5Nw==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:TOsm/JL1LXWgdYdodtruomjICML5p0kMeypCT+ZT5WLBR3Y3G94ZyoRs2G5MtL7Sz7Vvc8qeANe6q9hyhZpnNA==,iv:+0805CFm9/zEZO2ua1r2gCZ7STworggqSb29MvPjvwQ=,tag:L1xIw039OcqHBY2tznGjZA==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:g+uCFoeDNLxqyxsNaDXbJ+XWj33jLFKhAb1N8idoO9w=,iv:LHdWjiZe0FMIZKHkRJihL4ODde6TAu+vwC1vU3scEbI=,tag:pBTTiApOjDodQKGpimvK7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ2F2WGxmekJIL0dxTEs0
            My9YYlAxa3BTa1U5NTM2ZFBSVWtWeVAzeFhVCld3SE5OcFgyYUtFL08waHdmZ05s
            dHZDSkhET3NWZ0dtSmFmVlV2S0Y1YTAKLS0tIDhoM0RjYTZQQ056ZElzek5FRzh1
            QlpONm1EZVBxTVg4YU1IU1BBMzhxNEkKMspyTAKPrXbfyH07WUDfJJewGYrKk5B7
            iO/YOtCLS9jmkCRz5kH6ZUWHOPnDd9dri9jk7n+ub29JL4N2capxNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T20:26:04Z"
    mac: ENC[AES256_GCM,data:TYA/9HBcfNTsBHXBH8rDmVwKm21lfVdqi2uRe+t1mR3WHetaXnOCb5Hc+kPJgFSozE9AuC7TH2dLDsJLZ0BmOfB2tekoDWbkPtg3xtiPV3RxrHJ1imS9ayFG/dUzm9mNDNm453OU4TgdLLDs9xtm2o4MbJ/hil/5pd+qzN0RhZo=,iv:8mjeB/FXg8ATBk3GEMmvwjFzumet95Z9sfKp5lwUcNA=,tag:hAsrwJzxna692xo9Vewz0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
