apiVersion: v1
kind: Service

metadata:
  name: mastodon-elasticsearch
  namespace: medium-place
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: 8.4.1

spec:
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: mastodon

  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: http
