apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mastodon-elasticsearch
  namespace: medium-place
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/version: 8.3.3

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/part-of: mastodon

  template:
    metadata:
      annotations:
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+"
        diun.sort_tags: "semver"
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/version: 8.3.3

    spec:
      terminationGracePeriodSeconds: 60

      securityContext:
        fsGroup: 1001

      containers:
        - name: elasticsearch

          imagePullPolicy: Always
          image: bitnami/elasticsearch:8.3.3

          volumeMounts:
            - name: data
              mountPath: /bitnami/elasticsearch/data

          env:
            - name: ELASTICSEARCH_HEAP_SIZE
              value: 128m

          ports:
            - name: http
              protocol: TCP
              containerPort: 9200

  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
