apiVersion: apiregistration.k8s.io/v1
kind: APIService

metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    app.kubernetes.io/part-of: metrics-server

spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  version: v1beta1
  versionPriority: 100
  service:
    name: metrics-server
    namespace: kube-system
  insecureSkipTLSVerify: true
