apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: system:aggregated-metrics-reader
  labels:
    app.kubernetes.io/part-of: metrics-server
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"

rules:
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: system:metrics-server
  labels:
    app.kubernetes.io/part-of: metrics-server

rules:
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get

  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
