apiVersion: apps/v1
kind: Deployment

metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: metrics-server
    app.kubernetes.io/version: 0.6.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/part-of: metrics-server

  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-server
        app.kubernetes.io/part-of: metrics-server
        app.kubernetes.io/version: 0.6.1

    spec:
      serviceAccountName: metrics-server

      priorityClassName: system-cluster-critical

      volumes:
        - name: tmp 
          emptyDir: {}

      containers:
      - name: metrics-server

        image: k8s.gcr.io/metrics-server/metrics-server:v0.6.1
        args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s

        volumeMounts:
          - name: tmp 
            mountPath: /tmp

        ports:
          - name: https
            protocol: TCP
            containerPort: 4443

        livenessProbe:
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            port: https
            scheme: HTTPS
            path: /livez
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            port: https
            scheme: HTTPS
            path: /readyz

        resources:
          requests:
            cpu: 100m
            memory: 200Mi


