apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: metrics-server-auth-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: metrics-server

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader

subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
