apiVersion: v1
kind: Service

metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: metrics-server
    app.kubernetes.io/version: 0.6.1

spec:
  selector:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: metrics-server

  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
