apiVersion: v1
kind: Namespace

metadata:
  name: contour-private
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: contour-private
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./workloads/contour-private"
  interval: 60m
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  wait: true
 
