apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

metadata:
  name: kube-prometheus
  namespace: flux-system

spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./workloads/kube-prometheus"
  interval: 60m
  wait: true
  timeout: 3m0s
  retryInterval: 2m0s
  prune: true
  force: true
