pipeline:
  build-walg:
    image: alpine:3.16
    commands:
      - export WALG_VERSION=$(cat images/wal-g/VERSION)
      - docker build -f images/wal-g/Dockerfile -t forge.medium.place/nutria/wal-g:$WALG_VERSION .

