pipeline:
  set-walg-version:
    image: alpine:3.16
    commands:
      - export WALG_VERSION=$(cat images/wal-g/VERSION)

  build-walg:
    image: plugins/docker
    settings:
      repo: forge.medium.place/nutria/wal-g
      tags: $WALG_VERSION

