apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: photoprism
  namespace: medium-place
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: nutria.tail9b5a.ts.net
    projectcontour.io/websocket-routes: /
  labels:
    app.kubernetes.io/part-of: photoprism

spec:
  ingressClassName: private

  tls:
    - hosts:
        - gallery.medium.place
      secretName: gallery.medium.place-tls

  rules:
    - host: gallery.medium.place
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: photoprism
                port:
                  name: http
