apiVersion: apps/v1
kind: Deployment

metadata:
  name: synapse-signal-bridge 
  namespace: medium-place
  labels:
    app.kubernetes.io/name: signal-bridge
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/version: 0.4.0

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: signal-bridge
      app.kubernetes.io/part-of: synapse

  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: signal-bridge
        app.kubernetes.io/part-of: synapse
        app.kubernetes.io/version: 0.4.0  

    spec:
      volumes:
        - name: signald 
          emptyDir: {}
        - name: synapse-signal-bridge-config
          secret:
            secretName: synapse-signal-bridge-config
        - name: synapse-bridge-registration
          secret:
            secretName: synapse-bridge-registration

      containers:
        - name: mautrix-signal 
          image: dock.mau.dev/mautrix/signal:v0.4.0

          volumeMounts:
            - name: signald
              mountPath: /signald
            - name: synapse-signal-bridge-config
              mountPath: /data/config.yaml
              subPath: config.yaml
              readOnly: false
            - name: synapse-bridge-registration
              mountPath: /data/registration.yaml
              subPath: signal.yaml
              readOnly: false

          ports:
            - name: http
              protocol: TCP
              containerPort: 29328

        - name: signald 
          image: signald/signald:0.22.2

          volumeMounts:
            - name: signald
              mountPath: /signald
          
          envFrom:
            - secretRef:
                name: synapse-signal-bridge-env
