apiVersion: v1
kind: Secret
metadata:
    name: synapse-signal-bridge-env
    namespace: medium-place
data:
    SIGNALD_DATABASE: ENC[AES256_GCM,data:GHh+adrtt1luhPPdXABiSU5a4418HSpIWvICZBBUXAtT6L0kjDIA6fDGQFARC4nLlu0RWJWkhqv4PjKqlrhYoQ8Wrvh47mfgY9FzSrC3DV7JcfZ5LTk88BY0vhwVRsNDqNz7c2HYj3wPCLUhp+4FvMVReWOrzIHArBNBNkSQFDRxz0K15R2NK7UwNmYZFbdtFrpce+B3kgDKYOEiiZJrE6IxSEzBFQeuA+PO8T93r4ltveQiXHwERLw6SEXDxx9tXE1dCERF+JVmml6Y+s7ZvUfYZfjf1kek,iv:WDVYM8Ehuo3+YiepANGoFr9up0eNj02U6y4EFuUA2Gg=,tag:wzg82G8L51zTmRGOBB4+ZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR3Y4WTZnN3A3dDYzM3RN
            dUdTVUtCOFVvRjZqWTQxOSt6RnhEdGg5aHhBCm45cGVIVHNaRzlZVHl0bC96Ykx3
            V2toa1BoUkFldDQ2aC9VeVk0UzFNVHMKLS0tIEVWS0RmNlR5UVBUYkNzVnMzVTVn
            VjYyaW1WL0NNYlB6YnYydHMrMXVKTUkKMEdyv4LAvL+rLToc+h929x9YbPg2ytmG
            P0bkaAz1ee4vvP3NaD0KIy8Jp19plmRN7Z4KyFDDyI8K1W1bBSO2+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T20:26:04Z"
    mac: ENC[AES256_GCM,data:h+PQjdSWB+9QGIRSo8Vqlum4v9AmjdAzRkuYEsPmfDhshA0EpDHUvmf5K74BitDVsraqcBSpOTOj44Yb29LQQDMAtOXj/aFIzrzPXmhVBOc/jjkGOa3EpS1Yw4Ws1ILsyjVlVARShq8KmG3DOE3LTDmxbzOcS8Ytoa1XCFH8zQk=,iv:Ur2mlTlo3VXdNW90I1KteHnWaYhBk2adIicNcaEiJsE=,tag:kYcNPtYGCrO5xmw/pR1hRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
