apiVersion: apps/v1
kind: Deployment

metadata:
  name: paperless-ngx-gotenberg
  namespace: medium-place
  labels:
    app.kubernetes.io/name: gotenberg
    app.kubernetes.io/part-of: paperless-ngx
    app.kubernetes.io/version: 2.0.1

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: gotenberg
      app.kubernetes.io/part-of: paperless-ngx

  template:
    metadata:
      labels:
        app.kubernetes.io/name: gotenberg
        app.kubernetes.io/part-of: paperless-ngx
        app.kubernetes.io/version: 7.6.1

    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: gotenberg

          imagePullPolicy: Always
          image: gotenberg/gotenberg:7.6.1
          command:
            - gotenberg
            - --chromium-disable-routes=true

          ports:
            - name: gotenberg
              protocol: TCP
              containerPort: 3000
