apiVersion: v1
kind: Secret
metadata:
    name: synapse-bridge-registration
    namespace: medium-place
data:
    signal.yaml: ENC[AES256_GCM,data:w5v6fhU7EbBq/plhbEu2Fhb7vpShIs7xOzuehe+8/Pn0ocN46qkCMhhMFqMk0MSocfVnLtNq49uSTO61kVgrrd0P0L+hP2KAtBlolvq1UhdGjO872hznr01g+AZn/5D7iTdSTw8+OFgQyt0ItLNejuJ9R//QyDUVaIqKaw7GsTgMJSRIAs5bRTU9BYKVcaBBQmRjGXFOjWTAQuH7unvfZ2nenGQyng2Dpi9MUDgU83Gz7WI/ufditKOQFETX6mouecoCh09rQvYKbHUZ/KCjRZDlQhuC16n+YYeCSOco8CRe4Su8hDtNu3jJ3uIX6Nugm2z5d2sjJV1NJT4uvLUR53xW5/lVW2fijQ78V2J8dgAa4xtN0eI2URKocvSsPvZsbDCnEnwVbDQR+75309mhSlodLWv8ySsLUewlZjfpZj1/3zyqhNHYPgt1NuWblH9UGBcLHqdFX2oRepCb3MAsI41ub9xMWmrODTxxMjOgaNL3lw5rHXmdIaU3wJPFGdWHJp4tGeOwTz079zHzf/vZRCihaA4kepmuG3L/OP9XeMmKO3wc1KHnnI7Ij2GclfoxgICsL1j2GVk3YdtvkzkoioUkBnoKAwICzRsN919RKWf5DXzb6F2KwDpnIHwlJfYZP8vFnILqgCNuRMJuW0SwzwnDMnso1fb98HYcc3TZhMSmzRf/ZpboL/BDdjVGT8NY/2u56eVVoKMMjQ90TEZ7Xsbk1c+vDJ1mwjQnvL127Ne4wiVetXBnzmxE19bz3mng/Q8sESZyRkreKRBhHOBZjk4R659JZzqiLu7rRVPET278X9KREB1TW67I5gRIbcDs+qcuUM+Hvi2USLeAkqL2joKftNjCOBuIVXGyflrmdz5N/pFm22MwvA==,iv:kiyCM4kImXeP1CjjgFws0xbXdzdwzNtg0W7/lFWRwSk=,tag:Oxi+HbPHAC51CRBRl42QCQ==,type:str]
    facebook.yaml: ENC[AES256_GCM,data:Jd+QMIffNccZQWuZimvWLva5ZsPO2axUXz17x+z4VEt+rnCSTDo8ud0eHE8IzWsGdJHaYGVos/1K/vR9PMtZonnOllAX5YqTAz8CZnq6e6BWb2mS6W4KMdJ2SGlWLFC3ijm4PrwNuqmk55SYI3C0bwy5kM8HwZk1kPoAxGuOHiro/e4zyzQugmmTjHoBXMmqUIJCSefCacJP0aIfa95RASD+Tdc7cQzfT3GIh7mLO8gpEUausv3OQew6Ihbnfwmgq8waJySeNd/4gH4wJseb941dgVL+W5Nz+Bz2I6Hpu6OW5ypLmYIGeE/CJaenZG6ArvXqPcTBfbIjf6ErQ90pZ4X97BUR371F9QxLhUPBXA5UJHNeJaavzXeRJvfPU3h2y+PO143mzvpi2ub4CJmq8GebFU3/dYSIg+FwDjIf01F+sJLtX3PJDxL+v10WzpVLVZ8uj0ls8O1NtCkvRNA9e5/LDO7+mR6pfU/Gb+AYZ1c7PmrMbsvd0IXSVpYm6+YPwtj+myzaNWfd62MCFqD6fAfFAg3iz40ilml6JLKGdrHKUF202oLkV9rQBhjD/S+xbfjqY5OE87qax7J0TOzDtrfTPw1AsY9Ep8Inm5I4frb0V16O/bH7Ny0JOA/m4xB4S/Y+uKvnZtVaXWBrqCNTETh69kvi8rDwtS8jZ4qtyZG3rIH72TTGpZ1bL8oayJqq4kiO9QZnDv7U8am9rIpzcIkFKusrvkfIJyEukbEiTsZsUD8s5fQNXQeGVliXqus7X0MPKxyvn/8Kc2ZVNkyKadnYN3ErjVUV5cy1BBqNrfDLAgZaKxQ3W4cZ/H+CLo5pMZhkg62DJgqIZHJJNecqn//GFTWhZ7pe01UKdO7ISCDxIlWzPbleLuaDptvMEVWu,iv:sVmMHvAmyh6TzfsNSSITaYhH4Y81lm4Xl3hgvALs3bA=,tag:aDCqo2PvaSe5+5QwfHSXLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRksxSk1TbFVKYjNIUmh2
            R2pzTzgzU0xsM2piSWVSNDNZUE95dWVmc0JvCk1NRi9OcXRCM1NETHFIcEdXKzAz
            OGpISWdSVlAvNG9ScGMrQkIyWkY5bk0KLS0tIGV4alo3MWsxM0YxL056dWtiL09j
            OUp1MERuUzBIWUVqb3hLcGhDTUllSFkKiaWzPcWmqdFpjn1ihj2cOmRJDB2uCJyk
            e9b86Mp1o2yiujV1INSYqWb/MYgglCEOJTUKQMXtRz1Hga7amu+TzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T20:37:43Z"
    mac: ENC[AES256_GCM,data:D6YGRGEVab2G6JbGjfaG7jHjwddM/b2UY+p9sW5n+BuSLeDUAj4o91Sr4n4tOOqFWutyr1cFxsRN/nq/3XzEOHUsD2hL3o5bz1swNcHg/okhA4A0TO6adckT/yygeTegOR300ypWsnRndLeYv1Gpsz8d/onsP4wVm0krhEU4KTs=,iv:sbYRZuF0mv5E/P6Qimk0eERD//j3eAxvMiVLqXAOA7E=,tag:7fuEgKaKcA+/byIT+xbarw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
