apiVersion: v1
kind: Secret
metadata:
    name: synapse-bridge-registration
    namespace: medium-place
data:
    signal.yaml: ENC[AES256_GCM,data:bBWVYICNEPWCC8ldv/aEJeuQLRMkkQv02EE1oQo3ftCF2VBr1Q8savQMfTGm+XKNazM3SfKSzdL7zGyy9hifR6tUT0uFnf1y1yLMcfUwXFDhhcYGnqu7Z04OsMRXaRj5DjKCirVNiXkVRXx4xCm5H9idB84slzo9+BsCQotl6NkDg49LRSCH/1Rchz2QiFjrMuhwymf4V3eoDhK1uiPO6Cy3g+p8JanXf4SHGAqULHPvfILGctFflgUcNm/CwW63VvYAgAENkRF8aeLPBtIDmGMyUv5gAYlXfcKbX0LkbDn/HxWV+5nkulBl0btLyFq50kGQIy1Vkn5yLLl1AS1Y5U1yxnC+P15RCwqnZesc6yUbL6MEe46/whyIqETpTBIIDTV339ioyDcx8mmw+sA0x+R1xEE6bnbU9rttiOCZbHfV3uffpDcPbNxZYv9nNlZLP7k+znbRFKS6JLnKBjMuXbgeTtkLbB65sfGS5qD5VW2HpV6oo3/jzgQQ4p+0eH2Vn7Euon16MPTo/1NTBHLGNtv0a6yFbc/wZ1dVpt1JCw39NiYTmXGnu28dvDP7uMcz+MlMwoAKz4nA3IB2fGt7+53v7DwXw4pWSxiCJSdUU0qKI+ISTyulf8XVpR1Mg8IG+rUxksrDfobHd54Oq1dIRnE3Vm3PTc4ndYKAh9edCDM5uTjcH0rp4TSdMcHAlYA8r2Dr9z+HXkI1wgpAEo692CwTaxERb172U3q9uv5Zhu4DnMfLmjuFCnRoAAf3PNFOJOEJbNMz/Y/D3s/mdjm4dSeSMN/bjzYdPn5oDuQiqe70fuOfBnrr05GmluCZQlY79NhjgQQoPpE6OIBg9McmaRtO/lNj7YIYCk7rcz7lL1jFIDQWxOi13Q==,iv:r4D/xbliuhYxb2htMzqftYxp+nBXtR23EwysfygNPpo=,tag:gSCA1/UM3hvPJ9kQEZ05JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQVcvL3pKQzNLZTVzdDhu
            ZCtKZzhyRUdDaVVZTmc0VjhUM2hzdzJIYUNRCjh6U3UxeHgxcHUzaWVSTEpiYmVw
            U3A5WDVidHNzVmhlMWd4c2M0VGluSFUKLS0tIHlJOGNRZnN3d2JPcUcrZlRVV0dR
            UjczKzBlcm5SbFFpYVZSTVc0QXd6T3cKZuFg6LCtN2giWj+tP2khVC61NUi+q6eG
            Y5Z0QecL87fV4ZSB7rfU3BBROFAj864aR9tpqzxAJKi24WN3DpFtDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T17:59:08Z"
    mac: ENC[AES256_GCM,data:W5d+PhOiyd3HOovhgLdEvmGhGCZAHQVKaeJHZMPPFw1qLg+CXdm23p+ruQAvumDjE7vSyGE9DcYwh3Rc0CQrVzQZPL0IFxNztYqxMK0qXPKteD695bR08vS1EaMYiLobs6rfhXzabKC84eCGuxLtSUuk3SPHrSrjgeZtcDWJzdg=,iv:rm2hd6IEuPRt/znTFQEqVKH2mWvy9afi7Ztn17F5mOg=,tag:CFHpcURdePReXtc/fe5P+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
