apiVersion: v1
kind: Secret
metadata:
    name: synapse-bridge-registration
    namespace: medium-place
data:
    signal.yaml: ENC[AES256_GCM,data:YIAtFTraE+nrYmK5eP7/m0hPPngwbNWmM4jHp/N0+GL546bFOxkYCtq3DUci8Fo2CkqIUnV9jSEVqE4L9TSxEqghtTdG7MScNW9MHzN5pUSs3BLT9c/7LO9/Wk+FIxglKFYrz8LzGeDqnPwNMbCcOisW2FgE8/DuV9vvca2puY+hHLGLyvI67Zajnss0Q1TImPbUyNakufzNUTc4cyAy5NDwofFPktwJqU0Lk48vbxElip8QFB0KoMaNprx9xXSkmowNhLTVbtEHnwMGUHNAeHbWThtsXHZeyV4qK159D9hbQvyVaz77pT5KvChWefWL7OqOrXBIcUULZWuNmSjD3uTESTU6ByIOI14OhLo9sRsCjJwbxIfwyPbT/p9zhm/5ub7ygXRi+mNc2LpWMQRtp+YkG+AoCtzT8DUGzN9cjme9bWlpfRwFiGCwYKViDyuR4h9HJ7Am6X5qn5jsHtMfehUIPBHUSvMO8yW30rh+lsF+U3yP/qDW02w5eqzhha/4FjqMojkzI7gvajq5/FRvXG6Pb35teyMHnNuz3cD3TApNQz82N4mjszmrXlhZNSCKlJYJgrNyxAW8tNzfCrWDMaeX+NeAI3X/jkfDhISw1ZYYLyWNeWAVbyDQEyAo4m1EYutWuDGLx/4bjeFwNsBlb2Ren2bLopUJyd4iE14rPoYWtMf8U0pdTVZgN16hk7V3DDpyQ9nOJNOy4pB9vBNn0WwSLwNJaPmkJazfWdS0AE+GpyLoFfTo5hzQDC9wyBxc7vUOfVKBAfY/tg97UjjLF3FG1wSyuFW47yMwpTOvgEV2nlvOcuXnHVdxuI1bjzLMh8hfpYrdnSsq59W5FvPC0vHif6/PWaZB+mNEpucsvr2d6k+XYET+Ww==,iv:Yqk6ZdFP6lOtqxS7z5AAZ3aK1q173Notk2a7ClIFyk4=,tag:rejw0njGy0UW8uHY91DLZw==,type:str]
    facebook.yaml: ENC[AES256_GCM,data:8Y/9ywqA33Vs1vk4QWFxiXSey1uhnD23KnAq9t6rUnynDr5Gi/lXKzP5J03jLezsYJFETzxH4rYSSuguacNmXIeKNNgtv9M3Pv057fJsJ2elq1Le9Gte8YLQP5p2X4FeA8vQj60ZXFdppnJAmndwPBBOcBpTsZY3c7NZtZVxRlR9+gUBhL1Wd/uyrYvqWrFAT4dqcnMKp0qPjbRnJe5CZdyhVE5Vz3q3NnL0KLxZTd+WP1oBJIrJedDP8USbcJecGmux8kiYr/tDvU6A9JVP9OVZc8fA42kmbwZ+R02uipAZvyekKWILfnfcFY/VMM/E7fBzkwI+ahOEIPvji5NMNc8W761miE4zzG2ZmgdfCC57Cf9iQTR/TisGs4NrElPL8zsOwJcCkkBWgso/kyVpGYmpKxOFq4CIS+4B2jUuoUk4j5wZ2BlPVU+U1qkFz58EY4JuZCGGkNwnE+PMubOLRqE/z8YAGViWtQN1ggT7V68TgCnE1d4SAQMLhbis743EJoUFl8FY5OUwS8kH+PpJ6FCRDdKu5ApqEaN8kQmXqafgdy9WwC3ZdPm493tIeDzXskvCGWtShiGzqPcjEObgE4Du/YmtBwJ1v/oR9LoFNuNjuKWnqzTRyqJaWBUkz01TgmRk9ArCE/bNNPVTcP/0gNE6lcE/HubelhGEch8sQ2GPzMBfKyGOCMH7rlFjfAcccq5YUiNu5kcAtCdGzNgKvb83iwnV5+K0BnY9h3WypJt4hKvLmLgZzUGB9C2NFW9rOFvELJqwRe9pWViVBrPKmQtG45Ug6Nnw7SkkMUUQsXaDiWgsTtLZCYzhkQ5WhRH2SlN1hYhxkbjQOhVtmosZSmL4KWLQGX0iVRENm6/f4dL2aexKljh6T4xMiMhfuhUp,iv:nJMIO3V4v/5GKVO9PqnU2CBslBHbTCFFlvPbQz1Zjss=,tag:QMNIU17ksu5/gFEYWhpycQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRld6THYyUVZxKzlIRXZP
            czl3ZFAxRVB3akJNMmRvOHdDUU9UdjdQYmlRCjZ6SGVsK1p2aURHZ2dHOGNmQldP
            dnJmSGkrSFBwc2dVVjVkY2sxZzBxVncKLS0tIEpINXJOZ0FXYmZFdGVHRkg1L0lU
            VnJOS0Q4MGxTVldHTG5JTXFaRm9sWDAKi0aER4bs7+zkzBRgdpYM+QG9aDelPAvw
            CXyhMGjH8W9owrYIeab8ZHG6318Yx49VchL7jCu6VYWT4NOsW+giIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T21:17:32Z"
    mac: ENC[AES256_GCM,data:zEFihfdhfuS2paDhHryLS77Qt1e6z0y4lVyaOVlCEsc5uOT4JDLkblPrj7UjGlCCqOGVm41127eFMQf2p8JD5CPWpqdCH3cO5m4NgNHVcBunYvA3zi/belEFPCSsnXqaPejWBPvpxREOFa21jBF3Ysr4gzXDPhuKnzO5ytKWvcA=,iv:Oy6M4GEtFgghkeKND/CP2NAaXH3g35OL0xzMqCGqdTM=,tag:u+xGyjwugTjRbpp/w3OZgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
