apiVersion: v1
kind: Secret
metadata:
    name: teslamate-grafana-env
    namespace: medium-place
data:
    DATABASE_HOST: ENC[AES256_GCM,data:UfO8KpfUTw4sf0lnX3LSXYMF0OkmmKiknU2Nexd7EoK7UFYPTMq1cVGajblw8DOm5Xy3fw==,iv:AEBIqoQhjursSv+An45UQRv1otCMiScvOceXF7m1mEM=,tag:OpI5ZflRuRb2LRlpKR7uQg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:E7GT/YCLcc1JAbJ3hHZOMB4WmMu7DuSdiXET3eigkmI=,iv:TtVPZOj6ZEe3LuS0B/OaxpfsnaOujlQk/aJwGYJ2LbM=,tag:ipIhNhFCxmdE8RbYMapqcw==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:XX5tYLKJVweWkA9WNvxmcvDwWPjONElQuaEPUw+gi8qc6uGWyPpk9Rs8C5hDb4YW2Lg9GkfOq4VB6QFZJMNx5Q==,iv:mTr+PSE8CQol1BYXTvGsaSwvdQcZGwTbOaM43KPxnF8=,tag:Q2zBDrGe2FcgsCHqTkPE4Q==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:pmRyvq8IcV8JAuRuITu/gdiITFxxJJT/knBkRaG9hIs=,iv:KKCeSGe+YVUnl/AmBoNLVhfo2ZL5tYVGScOwN27RASY=,tag:9RDMZh4bjZVMrAvpsEF8Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ufcw42mtfu65grs30zqwu65xl7wczkllu3r4gjpk5yr7tr02q5kqq0pnvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cG1pa3EwU01VSEhudzZG
            MnRGUTZ5dE10UE10UVl6Z3lRNi8zRy91bEUwCkZXRWRXYVMxQ1hCbkNUUmVzK24r
            NkRkMVI5ZzhVVXA0aHBLNmhiZUdNYWsKLS0tIDI1WnJtOXFsYmsxdytpUGFlKzhz
            QTZ3cVpaQnpWeGh4c08zK1BXMERzNVEKuKo1Hai0RQDOAh5H924di751n8AV4N+y
            RNVSRiiKHjnVrsMYXrIYo+PdJUqVAmrlY3VuHn5p0eX8wa0i4kbSdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-23T00:03:59Z"
    mac: ENC[AES256_GCM,data:CjB7BvO77yrFLTSMFQSyjjl+i73gBwBZD1apRZKYJ2Zw/iT1oaeNdZfHq3DohfI78hEwsWi6h0gPB45vWGMX5UhMyC00b44r71Mr0Xm851kt9M691OioNN/TkMcHLb1YDQUIUZNKptZHJsHUFxv95RK8rgs8XlxULRwmKle9Sqk=,iv:KGlHRDn5Awf+G1yhCZT5EKOozmh/I80bvvwyJ7qGOo4=,tag:iOCD4THyV7xz+cmj9vmb0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
