name: Generate docs

on:
  push:

jobs:
  docs:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdBook
        uses: baptiste0928/cargo-install@v1
        with:
          crate: mdbook 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate docs
        run: mdbook build docs

      - name: Publish to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/book
          publish_branch: gh-pages
          cname: docs.nutria.cloud
