name: TruffleHog

on:
  - push

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TruffleHog
        uses: trufflesecurity/trufflehog@v3.14.0
        with:
          path: ./
          base: HEAD@{1}
          head: HEAD
