apiVersion: apps/v1
kind: Deployment

metadata:
  name: stolon-proxy
  namespace: stolon
  labels:
    app.kubernetes.io/name: stolon-proxy
    app.kubernetes.io/part-of: stolon
    app.kubernetes.io/version: 0.17.0

spec:
  replicas: 2
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/name: stolon-proxy
      app.kubernetes.io/part-of: stolon

  template:
    metadata:
      labels:
        app.kubernetes.io/name: stolon-proxy
        app.kubernetes.io/part-of: stolon
        app.kubernetes.io/version: 0.17.0
        stolon-cluster: nutria
        component: stolon-proxy

    spec:
      serviceAccountName: stolon-proxy

      terminationGracePeriodSeconds: 60

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - stolon-proxy

      containers:
        - name: stolon-proxy

          image: cschmatzler/stolon:0.17.0-pg14-r1
          command:
            - "/bin/bash"
            - "-ec"
            - "exec gosu stolon stolon-proxy"

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STPROXY_CLUSTER_NAME
              value: nutria
            - name: STPROXY_STORE_BACKEND
              value: kubernetes
            - name: STPROXY_KUBE_NAMESPACE
              value: stolon
            - name: STPROXY_KUBE_RESOURCE_KIND
              value: configmap
            - name: STPROXY_LISTEN_ADDRESS
              value: "0.0.0.0"

          ports:
            - name: postgresql
              protocol: TCP
              containerPort: 5432

          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            timeoutSeconds: 5
