apiVersion: v1
kind: Service

metadata:
  name: stolon-proxy
  namespace: stolon
  labels:
    app.kubernetes.io/name: stolon-proxy
    app.kubernetes.io/part-of: stolon
    app.kubernetes.io/version: 0.17.0

spec:
  selector:
    app.kubernetes.io/name: stolon-proxy
    app.kubernetes.io/part-of: stolon

  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
